### ISSUE TITLE
need a way to specify initial execution time for ConstantDelaySchedule

### ISSUE THREAD

**Issue by jizhilong** [robfig/cron#100]
Hi @robfig 
    As the title said, is there any way I can specify the initial execution time for a ConstantDelaySchedule, so that I can describe a job schedule as `from 2017-03-23 23:55:00+8:00, run at every 30 minutes`?

**Comment by monotone** [comment]
I need this feat too. but it seems count`t do this yet.  beacause the run() function calculates next run times for the jobs, always base on time.Now().  Not base on the specific time.

**Comment by robfig** [comment]
I guess you could do that with a combination:

```go
cron := cron.New()
cron.AddFunc("0 55 23 23 3", func() {
  cron.AddFunc("@every 30m", myFunc)
})
```
