### ISSUE TITLE
Go process need to stand by? Or else scheduled job will not be running?

### ISSUE THREAD

**Issue by lnshi** [robfig/cron#102]
Just read through the docs, so this is not an exactly Unix/Linux `crontab` style cron?

After I start the job runner, the go process still need to stand by there forever, or else all the scheduled job will not be running? Not like handling over the control to os, then even the go program exit, os will still invoke the jobs as scheduled periodically？

Like:
```
func main() {
  c := cron.New()
  c.AddFunc("* * * * * *", func() { fmt.Println("?????????????????????????") })
  c.Start()
  time.Sleep(time.Second * 50)
}
```

Then go program exit, nothing is there....

Am I correct?

**Comment by robfig** [comment]
Correct

**Comment by lnshi** [comment]
Thanks for the confirmation.
