### ISSUE TITLE
"@every" is starting from program start

### ISSUE THREAD

**Issue by gravis** [robfig/cron#104]
Hi,

We noticed a weird behaviour, or at least something worth documenting:

`@every 12h` is going to run every 12h, from the program start, so it's not equivalent to 1 run at midnight and 1 at noon (which we expected).

Thanks

**Comment by robfig** [comment]
Thanks for pointing it out. It's operating as intended, but I guess it's not explicitly called out and I can see how it's not clear. I'll add a sentence to the docs.

**Comment by gravis** [comment]
Thanks!
