### ISSUE TITLE
feature: from the end of the month

### ISSUE THREAD

**Issue by rbucker** [robfig/cron#105]
I know the CRON expressions are modeled after CRON, however, I have a basic need to schedule events at the end of the month. Some times the last day and some times the last 4 or 5 days. As of systemd 233 they added a '~' to the expression syntax to support exactly that. Any chance of getting that included?

**Comment by robfig** [comment]
I'm not familiar with that feature, but pull requests welcome! (I don't have the bandwidth to continue development myself at this time, sorry)
