### ISSUE TITLE
The function multiple starts immediately after add into cron

### ISSUE THREAD

**Issue by austinov** [robfig/cron#106]
I'm trying to add function into CRON to running every minute:
```c.AddFunc("*/1 * * * *", func() { log.Println("Run every minute") })```

If I do it immediately after cron object was created, then code works as expected - the function will be executed every minute, starting at the beginning of the next minute.
But if I will add the function in a minute after the current (or later - after 2, 3 and more minutes), it begins to execute immediately after you add into the cron.
In addition, it executed as many times as the minutes passed between the creation of the cron and function was added.
For example, if you try to run the following code:
```
package main

import (
        "log"
        "time"
        "gopkg.in/robfig/cron.v2"
)

func main() {
        c := cron.New()
        c.Start()
        log.Println("Start CRON.")
        time.Sleep(2 * time.Minute)
        log.Println("Add function into CRON.")
        c.AddFunc("*/1 * * * *", func() { log.Println("Run every minute") })
        time.Sleep(5 * time.Second)
        c.Stop()
}
```

So, the function will call exactly 2 times immediately after adding into cron, because it took 2 minutes between the start of the cron (12:31:36) and adding the function into it (12:33:36).
```
2017/05/29 12:31:36 Start CRON.
2017/05/29 12:33:36 Add function into CRON.
2017/05/29 12:33:36 Run every minute
2017/05/29 12:33:36 Run every minute
```
If between execute `c.Start()` and `c.AddFunc` took 3 minutes, then we would see in the logs three calls `Run every minute`.
In my opinion, the first time the function should be executed at the beginning of the next minute - **12:34:00** and repeat every minute.

**Comment by austinov** [comment]
Excuse me, it was fixed in master, but not in v2.
Would you fix it in v2?

**Comment by robfig** [comment]
I agree that it is a bug. v3 branch has this fix, and it has other fixes too. I recommend upgrading to it.
