### ISSUE TITLE
Feature request: port v2 features into master

### ISSUE THREAD

**Issue by tamalsaha** [robfig/cron#111]
Thanks for this wonderful library. But we would like to request that you port v2 features into master branch. For our use-case we need to be able to remove cron functions. This feature is available in v2 branch. But v2 branch has a critical bug which causes multiple invocation: https://github.com/robfig/cron/issues/106

I also noticed that there are various changes in master branch that are not available in v2. It seems that master branch is the maintained branch. It will be greatly appreciated if you would add support for deleting cron schedules on the master branch.

cc: @sadlil @aerokite

**Comment by cskr** [comment]
#110 has a workaround that won't require changes to how Jobs are stored in memory. See if that fits your use-case.

**Comment by 3junit** [comment]
@cskr  But if i need to add and remove jobs in runtime? I mean smth like 
- init cron
- add cron jobs
- read channel
- on channel got info - add new cron job or remove already exists

**Comment by cskr** [comment]
@3junit You can already [schedule new jobs](https://godoc.org/github.com/robfig/cron#Cron.Schedule) after a Cron has been created.

**Comment by 3junit** [comment]
@cskr But i need to stop job that already in scheldule! Like switch it off. But it keep running. I need to reinitialize cron if need to stop runnig job (test it on * */1 * * * jobs) and i need correct cron instruction? ( i mean change * */1 * * * to * */10 * * * for example) 
That cron.remove(id) would be awesome!

**Comment by cskr** [comment]
@3junit Yes, but unfortunately there is no ID for jobs in the current API. I didn't want to break compatibility in #110.

**Comment by robfig** [comment]
This is implemented in v2 and v3, so I think this use case is handled. Please give v3 a shot!
