### ISSUE TITLE
it's possible schedule just run once?

### ISSUE THREAD

**Issue by ipiao** [robfig/cron#114]
i think it's reasonable for schedule just run once?or run at given time,like five days later,and just once.

**Comment by hongmaoxiao** [comment]
@ipiao come to my fork here, https://github.com/makelifemorefun/cron I haven implement that, but readme not added yet.

**Comment by ipiao** [comment]
thank you @hongmaoxiao

**Comment by hongmaoxiao** [comment]
@ipiao you can read the cron_test.go to use it now,  add a specific cron name "test", after it runs, just invoke cron.RemoveJob("test") to remove it.
<img width="799" alt="2017-08-31 10 37 54" src="https://user-images.githubusercontent.com/3943494/29903996-46ec4aae-8e39-11e7-9ac9-554a19704a50.png">
