### ISSUE TITLE
iterative AddFunc , the  parameters will be cover

### ISSUE THREAD

**Issue by kingangelAOA** [robfig/cron#115]
func test(a int, t int64) {
	fmt.Println(a, t)
}

func main() {
	runTime := 8760

	endFlag := time.After(time.Duration(runTime) * time.Hour)
	c := cron.New()
	addresses := []int{1, 2, 3, 4, 5, 6}
	for index, a := range addresses {
		fmt.Println("begin:", a)
		ft := fmt.Sprintf("%d */%d * * * ?", index, 1)
		c.AddFunc(ft, func() {
			test(a, time.Now().In(c.Location()).Unix())
		})
	}

	c.Start()
	<-endFlag
	c.Stop()
}

result:
begin: 1
begin: 2
begin: 3
begin: 4
begin: 5
begin: 6
6 1504607160
6 1504607161
6 1504607162
6 1504607163
6 1504607164
6 1504607165

expect:
begin: 1
begin: 2
begin: 3
begin: 4
begin: 5
begin: 6
1 1504607160
2 1504607161
3 1504607162
4 1504607163
5 1504607164
6 1504607165

**Comment by hongmaoxiao** [comment]
func test(a int, t int64) {
	fmt.Println(a, t)
}
func main() {
	runTime := 8760

	endFlag := time.After(time.Duration(runTime) * time.Hour)
	c := cron.New()
	addresses := []int{1, 2, 3, 4, 5, 6}
	for index, a := range addresses {
		fmt.Println("begin:", a)
		ft := fmt.Sprintf("%d */%d * * * ?", index, 1)
		go func(i int) {
			c.AddFunc(ft, func() {
				test(i, time.Now().In(c.Location()).Unix())
			})
		}(a)
	}

	c.Start()
	<-endFlag
	c.Stop()
}

**Comment by hongmaoxiao** [comment]
I think the right way is:
func test(a int, t int64) {
	fmt.Println(a, t)
}
func main() {
	runTime := 8760

	endFlag := time.After(time.Duration(runTime) * time.Hour)
	c := cron.New()
	addresses := []int{1, 2, 3, 4, 5, 6}
	for index, a := range addresses {
		fmt.Println("begin:", a)
		ft := fmt.Sprintf("%d */%d * * * ?", index, 1)
		go func(i int) {
			c.AddFunc(ft, func() {
				test(i, time.Now().In(c.Location()).Unix())
			})
		}(a)
	}

	c.Start()
	<-endFlag
	c.Stop()
}



begin: 1
begin: 2
begin: 3
begin: 4
begin: 5
begin: 6
1 1504610940
2 1504610941
3 1504610942
4 1504610943
5 1504610944
6 1504610945

**Comment by kingangelAOA** [comment]
thanks

**Comment by flybaozi** [comment]
thks！！！

**Comment by marcesher** [comment]
Thanks @hongmaoxiao !
