### ISSUE TITLE
Cannot have the function triggered

### ISSUE THREAD

**Issue by lucj** [robfig/cron#116]
First of all thanks for the lib, it's great.

I had the following code working fine for a couple of months but it seems the function is not triggered anymore. Log with current day / time is never displayed.

It's running the Docker image golang:1.9-alpine.

```
    // Check every minute if update of devices' state need to be done
    c := cron.New()
    c.AddFunc("0 * * * * *", func() {
        // Get current day and time, ex: 3 / 18:00 => Wednesday / 18:00
        now := time.Now()
        time := now.UTC().Format("15:04")
        day  := strconv.Itoa(int(now.Weekday()))
        fmt.Printf("### CURRENT DAY: %s / TIME (UTC): %s\n", day, time)

        // Do some stuff
        doSomeStuff()
    })
    c.Start()
    defer c.Stop()
```

Anything I'm missing ?

**Comment by robfig** [comment]
Sorry for the long delay, but I'm not sure how to diagnose this. Please let me know if you still see a problem. I'm developing an update to this library on the v3 branch which is intended to solve all outstanding issues, so I would very much appreciate any information about things which are wrong.
Thank you!

**Comment by guanfeng36** [comment]
I have the same issue
```
func main() {                                                                                                              
        c := cron.New()                                                                                                    
        c.AddFunc("*/5 * * * * ?", func() { fmt.Println("Every hour") })                                                   
        fmt.Println("test11")                                                                                              
        c.Start()                                                                                                          
        defer c.Stop()                                                                                                     
        select {}                                                                                                          
        fmt.Println("test")                                                                                                
                                                                                                                           
        select {}                                                                                                          
}
```       
go version go1.9 linux/amd64
Is there any problem in code?

**Comment by robfig** [comment]
Which version of cron are you using? Can you verify that this still happens with the v3 branch? There have been some fixes in the past. Also, can you provide the last time the job run, which was printed? Then I could add a unit test to verify the schedule chooses the correct time after that timestamp. Thanks

**Comment by robfig** [comment]
If anyone can reproduce with v3, please let me know. I'm not able to reproduce this as-is and I'm going through cleaning up old issues, so closing this as not-actionable for now.

**Comment by augustine0890** [comment]
I guess the problem is running with a Docker image, but I don't know how to fix that.

**Comment by augustine0890** [comment]
> First of all thanks for the lib, it's great.
> 
> I had the following code working fine for a couple of months but it seems the function is not triggered anymore. Log with current day / time is never displayed.
> 
> It's running the Docker image golang:1.9-alpine.
> 
> ```
>     // Check every minute if update of devices' state need to be done
>     c := cron.New()
>     c.AddFunc("0 * * * * *", func() {
>         // Get current day and time, ex: 3 / 18:00 => Wednesday / 18:00
>         now := time.Now()
>         time := now.UTC().Format("15:04")
>         day  := strconv.Itoa(int(now.Weekday()))
>         fmt.Printf("### CURRENT DAY: %s / TIME (UTC): %s\n", day, time)
> 
>         // Do some stuff
>         doSomeStuff()
>     })
>     c.Start()
>     defer c.Stop()
> ```
> 
> Anything I'm missing ?

Please post the Dockerfile for building the image here.
