### ISSUE TITLE
Monitor the state of the cron job and start a cron job from ID ahead of schedule

### ISSUE THREAD

**Issue by elvarb** [robfig/cron#117]
I have a long running job that can run for days. The cron scheduler only kicks of a process based on the cron string itself. If for example my long running job does not complete I want to have a go routine that checks if the function is running or not and if not I want it to start the cron task even though the next run time is many days from now.

Is it possible with this library?

I can poll the defined schedules but I have not seen any way to do more.

**Comment by robfig** [comment]
Hi, I'm afraid that is not possible with this library. You would have to accomplish that entirely in your own code. Sorry!
