### ISSUE TITLE
Is it possible to run the function first and then start cron?

### ISSUE THREAD

**Issue by paulolimarb** [robfig/cron#119]
Hello

Is it possible to run the functions first and then start cron?

        f := func() {
		fmt.Println("My first func")
	}

	s := func() {
		fmt.Println("My second func")
	}
		
	b := cron.New()

	b.AddFunc("0 * * ? * *", f)
	b.AddFunc("0 * * ? * *", s)
	
	b.Start()

Thanks

**Comment by robfig** [comment]
https://github.com/robfig/cron/issues/160#issuecomment-502447951
