### ISSUE TITLE
First start time problem

### ISSUE THREAD

**Issue by ffest** [robfig/cron#121]
I found the line in doc about "@every" - For example, "@every 1h30m10s" would indicate a schedule that activates immediately, and then every 1 hour, 30 minutes, 10 seconds.
But first start takes place only after this period of time.
For example,
```
c := cron.New()
c.AddFunc("@hourly", func() { fmt.Println("Every hour") })
c.AddFunc("@every 1h30m", func() { fmt.Println("Every hour thirty") })
c.Start()
```

The first line will be after hour only.
Is it operating as intended?

**Comment by ernsheong** [comment]
Probably good by design, if you have a lot of jobs then all those jobs running the same time on start may cause server to be burdened on initialize.

**Comment by ffest** [comment]
I agree with you, but in doc the line "schedule that activates immediately, and then..."  tells us about the opposite. So the question is still open.

**Comment by adam-hanna** [comment]
I agree, the documentation is confusing. I interpreted it the same way as @ffest. Would suggest removing, "schedule that activates immediately" from the docs.

**Comment by robfig** [comment]
Whoops, good catch. Thanks

https://github.com/robfig/cron/commit/b41be1df696709bb6395fe435af20370037c0b4c
