### ISSUE TITLE
7 should be Sunday also

### ISSUE THREAD

**Issue by danielkucera** [robfig/cron#122]
Standard Linux cron permits using number 7 as Sunday too: https://linux.die.net/man/5/crontab

**Comment by mroach** [comment]
@danielkucera Using 7 for Sunday is considered non-standard and isn't supported by all cron engines. If you can, avoid using it since it can lead to confusion, especially if you also use 0 for day of week.

**Comment by robfig** [comment]
I think the documentation on this package is clear enough that any momentary confusion could be resolved. I don't see a big advantage in supporting 7 for Sunday as well. Sorry!
