### ISSUE TITLE
A job has been added, how can i cancel it ???

### ISSUE THREAD

**Issue by ccpwcn** [robfig/cron#124]

**Comment by ffest** [comment]
When you add job you can get job's ID, so after you can use method remove to cancel it
`id, err := cron.AddFunc("some_interval" , func() {}) `
`cron.Remove(id)`

**Comment by zhou88qiao** [comment]
cron.Remove   I have no found the function.  And  cron.AddFunc has return err, no id
func (c *Cron) AddFunc(spec string, cmd func()) error {
	return c.AddJob(spec, FuncJob(cmd))
}

**Comment by zhou88qiao** [comment]
how to remove a job

**Comment by besser** [comment]
Hi, If you see de file cron.go of v2 branch, you'll find the Remove funcion and the Id return on AddFunc Function! 

https://github.com/robfig/cron/blob/v2/cron.go

The question is if the v2 branch was finished...

**Comment by rjain15** [comment]
@besser, I need the remove and the Add job with name methods, which you implemented in your https://github.com/besser/cron 
Can I use your repo or are you sending a pull request to this repo...

**Comment by besser** [comment]
@rjain15, of course you can use the code from my repo and soon I will send a pull request to the this repo.

**Comment by damdo** [comment]
@besser News about your pull request? Thanks.

**Comment by besser** [comment]
Done!

Sorry by my late.

**Comment by robfig** [comment]
With the version on master, in this repo, you would have to Stop() and create a new Cron with the jobs you want. I hope to develop v2 further (using vgo, at a different package path) to enable this capability.
