### ISSUE TITLE
how to use in everday with start time and end time every 5 seconds ?

### ISSUE THREAD

**Issue by jjjachyty** [robfig/cron#125]
i want func AA() every 5 seconds in eveday at 11:30:25 and end at 15:30:25？ @harshal @blackskad @dennisfrancis @elimisteve @tdterry

**Comment by robfig** [comment]
I think you would have to combine multiple schedules to do that. As in, add the same job multiple times with schedules that add up to your desired one.

```
25-59/5 30 11 * * ?
*/5 31-59 11 * * ?
*/5 * 12-14 * * ?
*/5 0-29 15 * * ?
0-25/5 30 15 * * ?
```

This is untested, but you could write a unit test to verify or disprove that.

**Comment by sandyydk** [comment]
@robfig  Sorry for the trouble. I am not able to run a cronb like very 5 minutes everyday every year. 
tried this -
0 0/5 0 * * *

Doesn't seem to work.
