### ISSUE TITLE
Am I doing this wrong? every 5th minute

### ISSUE THREAD

**Issue by alexellis** [robfig/cron#127]
I was following the sample.. 

This expression should be (once) every 5th minute according to Linux cron, but I'm getting it firing continually.

```
c.AddFunc("*/5 * * * *", func() { fmt.Println("Every 5th") })
```

I also saw this mis-fire during the "26th minute" of the hour:

```
c.AddFunc("24 * * * *", func() { fmt.Println("Every 24th minute") })
```

Probably I'm doing this wrong, please could you comment?

https://crontab.guru/#*/5_*_*_*_*

**Comment by se3000** [comment]
This library supports [granularity at the second level](https://godoc.org/github.com/robfig/cron#hdr-CRON_Expression_Format). Try `0 */5 * * * *`.

**Comment by radu-munteanu** [comment]
You can use the standard cron spec using `ParseStandard()` function.

**Comment by alexellis** [comment]
Thanks all.. as I think other people have mentioned - a brief README would do wonders for usability.
