### ISSUE TITLE
How to prevent job "stacking"

### ISSUE THREAD

**Issue by genexp** [robfig/cron#129]
If I have a job that runs once every 10 seconds, and a single invocation takes 15 seconds to complete, I assume the second will run on top of the first.  What's a good way to skip the second invocation if the first hasn't completed yet.

**Comment by cyanly** [comment]
one example way is to use something like atomic boolean flag at beginning of your job func:
https://github.com/tevino/abool

**Comment by robfig** [comment]
Exactly this. You can implement more complicated coordination behind the Job interface as easily as it could be provided as an option.
