### ISSUE TITLE
Set Timezone for Scheduler

### ISSUE THREAD

**Issue by ericuldall** [robfig/cron#132]
Is there a way to set the timezone used by the scheduler?
For instance if I was to use `0 0 4 * * *` to run a cron at 4am every day that would default to UTC (or system clock) I assume. However, I would like a way to default the timezone used by cron to another region. Is this possible?

**Comment by radu-munteanu** [comment]
It's possible.

You can use NewWIthLocation() to create a Cron object with a different time zone
```
...
l, _ := time.LoadLocation("US/Central")
c := cron.NewWithLocation(l)
c.Schedule(schedule, cron.FuncJob(...))
c.Start()
```

**Comment by ericuldall** [comment]
Actually, I'm running this `FROM scratch` in Docker and have a feeling the tz database is not present. I'm going to follow that theory, but please let me know if you think it's something else.

**Comment by ericuldall** [comment]
Missing tz data was the issue. I was able to fix it with the following Dockerfile (in case someone else has the same problem):
```
FROM alpine:latest as alpine
RUN apk --no-cache add tzdata zip ca-certificates
WORKDIR /usr/share/zoneinfo
# -0 means no compression.  Needed because go's
# tz loader doesn't handle compressed data.
RUN zip -r -0 /zoneinfo.zip .

FROM scratch

ENV ZONEINFO /zoneinfo.zip
COPY --from=alpine /zoneinfo.zip /

ARG bin
ENV bin ${bin}

COPY ${bin} /${bin}
```

Everything seems to be working now. Thanks for the help!

**Comment by radu-munteanu** [comment]
You should always handle errors so you don't get panics. In my basic example, I just skipped them.

**Comment by lispc** [comment]
The api has changed like below now.
```
c := cron.New(cron.WithLocation(time.UTC))
```

**Comment by andersc** [comment]
is ->
loc, err := time.LoadLocation("Europe/Stockholm")
c := cron.New(cron.WithLocation(loc))

Then you run the program for a year. Is then the cron job compensating for daylight saving events for the IANA code provided?
