### ISSUE TITLE
Create a new release ?

### ISSUE THREAD

**Issue by JigSawFr** [robfig/cron#134]
Hello !
Thanks for your great script,
But some app use only releases and your's seems very outdated (2013)
Can you publish a new release containing your changes ?
Thank you

**Comment by hongmaoxiao** [comment]
@JigSawFr Clone and write it yourself is the best way, I think.

**Comment by JigSawFr** [comment]
It will not change anything,
3rd party as Rancher use this repository for example, but with the latest release available.

**Comment by robfig** [comment]
Done, thanks
