### ISSUE TITLE
How can I do graceful restart?

### ISSUE THREAD

**Issue by rahulxxarora** [robfig/cron#138]
Hi @robfig , thanks for developing this awesome library. I am planning on using this library for my future project. But, I am unable to understand that how will I update my tasks gracefully using this library?

By gracefully, I meant that the running tasks shouldn't be terminated and when the cron starts again, it should follow the original timetable.

Ex:
Lets say a cron runs every 30 seconds. Now to update the tasks I restart it at 20 seconds. Then it should again execute the task after 10 seconds.

I would really appreciate your help on this. Thanks.

**Comment by robfig** [comment]
In my use cases, I wouldn't worry about it. You could sleep for 30s to ensure they aren't executed too close together, or run it immediately if it doesn't matter. Out of curiosity, what is your use case that is so sensitive to being run exactly every 30 seconds?

If you know it's a 30 second interval, you could save the timestamp that it was originally started, or coordinate between the job's goroutine and the one running the cron using a channel, and Stop/Start the cron at that time.

**Comment by mwmahlberg** [comment]
@rahulxxarora Wouldn't this simply translate to `0,30 * * * * *`?
