### ISSUE TITLE
Schedule Times more than just next

### ISSUE THREAD

**Issue by pjebs** [robfig/cron#142]
`Entries()` provides just the past time and the next time.

Can you point me the right direction on how I can extend it so I can get the scheduled time for the `N` times?

**Comment by robfig** [comment]
Untested, but something like this should work:

```go
spec := "* 0 0 0 0 0 ?"  // your cron spec
schedule, _ := cron.Parse(spec)
t := time.Now()
for {
  t = schedule.Next(t) 
  fmt.Println(t)
}
```
