### ISSUE TITLE
/0 in string causes Parse to hang indefinitely

### ISSUE THREAD

**Issue by FuzzyStatic** [robfig/cron#144]
Using a /0 incrementer in the schedule string causes the Parser to hang indefinitely

```go
schedule := "TZ=America/New_York 15/0 * * * * *"

_, err := cron.Parse(schedule)
if err != nil {
     return err
}
```

Expected behavior would be a non-nil error returned.

**Comment by robfig** [comment]
Thank you for the bug report, and sorry for the long delay. This has since been fixed, and I've added a test for it.
