### ISSUE TITLE
cron.Start() called multiple times executes jobs multiple times

### ISSUE THREAD

**Issue by robbbsen** [robfig/cron#158]
Hi everyone.

I've run into a strange (not intuitive behaviour) when calling `.Start()` multiple times.
This is a short example of my code:

```
func main() {
	fmt.Println("Hello, playground")
	init()
}

var cronGlobal *cron.Cron

func init() {
	cronGlobal = cron.New()
	cronGlobal.Start()
	cronGlobal.AddFunc("0/5 * * ? * *", someJob)
	
	// Notice I've called .Start() a second time in here (yeah, was a mistake)
	cronGlobal.Start()
}

func someJob() {
	fmt.Println("Executing interval [testing1]:1")
	// some stuff
	fmt.Println("-------------------------------")
}
```

This is my console output:

```
17.10.2018 16:29:15 | Executing interval [testing1]:1
17.10.2018 16:29:15 | Executing interval [testing1]:1
17.10.2018 16:29:15 | -----------------------------------------------
17.10.2018 16:29:15 | -----------------------------------------------
17.10.2018 16:29:20 | Executing interval [testing1]:1
17.10.2018 16:29:20 | Executing interval [testing1]:1
17.10.2018 16:29:20 | -----------------------------------------------
17.10.2018 16:29:20 | -----------------------------------------------
17.10.2018 16:29:25 | Executing interval [testing1]:1
17.10.2018 16:29:25 | Executing interval [testing1]:1
17.10.2018 16:29:25 | -----------------------------------------------
17.10.2018 16:29:25 | -----------------------------------------------
17.10.2018 16:29:30 | Executing interval [testing1]:1
17.10.2018 16:29:30 | -----------------------------------------------
17.10.2018 16:29:35 | Executing interval [testing1]:1
17.10.2018 16:29:35 | -----------------------------------------------
17.10.2018 16:29:40 | Executing interval [testing1]:1
17.10.2018 16:29:40 | Executing interval [testing1]:1
17.10.2018 16:29:40 | -----------------------------------------------
17.10.2018 16:29:40 | -----------------------------------------------
```
_I won't comment the events at 16:29:30 (only one execution?)._

My code is bigger than this and **I did the mistake to call `.Start()` two times**. Away from the point that this is a mistake by myself this is a unexpected (and not intuitive) behaviour.

From the view of OOP the `cron-object` is a worker that deals with multiple jobs that I register/add. If I accidently call `.Start()` two times **it should either throw an error or just ignore it instead of doing the registered/added jobs twice**.

This is an opinion-based thing but I'm fairly sure others will think about this the same.
Thank you very much.

**Comment by robfig** [comment]
Sorry for the long delay, but I believe this should be fixed in the v3 branch. Feel free to give it a shot and let me know if you see anything wrong!

**Comment by cute-angelia** [comment]
the v3 version (v3.0.1) also happend multiple times execute 

```
cron.New(cron.WithSeconds())
t.AddTask("* 45 0 * * *",  func)

```

**Comment by robfig** [comment]
Hi, this is not enough information for me to help you.

When submitting a bug report:
- Please provide a complete program that I can run
- Please say what behavior you saw
- Please say what behavior you expected

Thanks!

**Comment by hwkim1127** [comment]
> the v3 version (v3.0.1) also happend multiple times execute
> 
> ```
> cron.New(cron.WithSeconds())
> t.AddTask("* 45 0 * * *",  func)
> ```

It's just that you have set "* 45 0 * * *" which means EVERY SECOND. replace the first * to 0
