### ISSUE TITLE
Have ability to run cron at startup

### ISSUE THREAD

**Issue by holtwilkins** [robfig/cron#160]
This may be a dupe of https://github.com/robfig/cron/issues/119 , and if so I apologise.

I'm proposing a feature request: an `@startup` or `@immediate` or something similar keyword.  Namely, run the function as soon as the cron service starts (in addition to any other schedule provided, of course).

In some Linux implementations of cron there's a `@reboot` flag which I'm sort of trying to emulate here.  This flag could be called `@reboot` too, though that might be confusing.

**Comment by dana321** [comment]
Call a go routine on startup instead? You don't need this library to do that!

**Comment by holtwilkins** [comment]
Ha, that's true, but if I want the cron schedule / calling of go routine on startup to be conditional on external config, then I do.  We pass-in an external config file that may or may not have a list of cron schedules to run various goroutines on, and some of those schedules may or may not be "run this on startup".

**Comment by junkiebev** [comment]
I prefix jobs I want to run at startup with a `!` character and execute the desired task by calling the function directly. I then I override the schedule string
```
sch = strings.TrimLeft(sch, "!")
```

**Comment by robfig** [comment]
I would like to stick to the cron spec without adding one-off features, especially because this can be easily done outside of cron with a custom prefix as suggested by @junkiebev or a separate bit. Sorry!

**Comment by kleijnweb** [comment]
What about `@reboot`?
