### ISSUE TITLE
@midnight is only triggered during weekdays

### ISSUE THREAD

**Issue by Entrio** [robfig/cron#162]
I am really at a loss here, I have my cron set up as follows (I am using v1):

`
c := cron.New()
	cron.NewWithLocation(&time.Location{})
	log.Infof("Current system time is: %s",time.Now().Local().Format("2006-01-02 15:04:05"))

	if err := c.AddFunc(subenv.Env("CRON_PERIOD", "@midnight"), func() {
		if err := Crontask.CalculateForDate(time.Now().Local().AddDate(0, 0, -1)); err != nil {
			log.Warnf("Error during redemption cron! Error %s", err.Error())
		}
	}); err != nil {
		log.Fatalf("Failed to add cron task! Error: %s", err.Error())
	}

	c.Start()
	log.Infof("CRON service started (%s)", subenv.Env("CRON_PERIOD", "@midnight"))
`

subenv.Env("CRON_PERIOD", "@midnight") - gets value of CRON_PERIOD env variable

In my log message I get message: CRON service started (@midnight)

Desired result: for cron to run my function every day at 00:00:00
Outcome: cron only runs on weekdays

Could not find anything in the documentation in regards to this

**Comment by ngethe** [comment]
Did you solve this?? I am having the same issues (someone was joking that my server is serious on labor laws and it was taking the weekend off)

I have almost the same code

**Comment by junkiebev** [comment]
I use `@daily` for midnight executions - it seems to work.

**Comment by ngethe** [comment]
@junkiebev please share your code so that I can see what I missed

**Comment by junkiebev** [comment]
IDK how useful it will be, but this is a well-documented project I'm running with it
[Github project](https://github.com/junkiebev/multi-cron)
[Dockerhub repo](https://hub.docker.com/r/jeffkolb/multi-cron)

I'm on v2 though :-/

**Comment by junkiebev** [comment]
What happens if you specify `0 0 0 * * *`?

**Comment by robfig** [comment]
This seems like a severe bug, but I can not reproduce. I added unit test cases for this and they passed. If you could provide a test case demonstrating the issue, I would be very happy to solve it for you.

**Comment by robfig** [comment]
The only thing I can suggest is to use the v3 branch, which has some fixes from earlier versions. If you can post a complete program that reproduces (and tell me your local time zone), I'm happy to investigate further. Sorry for the trouble!
