### ISSUE TITLE
Where does the inspect() function come from?

### ISSUE THREAD

**Issue by MichaelHipp** [robfig/cron#163]
The godoc.org documentation contains this line:
```
// Inspect the cron job entries' next and previous run times.
inspect(c.Entries())
```

Where is this inspect() function to be found?

**Comment by robfig** [comment]
It's just a hypothetical user-provided function that you can write which iterates through the entries and prints them or something. I guess using fmt.Println would have been clearer in that doc..

**Comment by zheeeng** [comment]
As a newbiew, the doc make me thought it is a built-in golang function.

**Comment by gtbio** [comment]
ok
