### ISSUE TITLE
quartz support

### ISSUE THREAD

**Issue by llonchj** [robfig/cron#164]
Does the library support quartz? If not, what will be the advice to get it implemented?

**Comment by robfig** [comment]
What does that mean?

**Comment by llonchj** [comment]
quartz is a cron format flavour that adds more expressivity to scheduling. Has 2 extra fields, seconds and optional year (6-7 fields in total). [Quartz](http://www.quartz-scheduler.org/documentation/quartz-2.x/tutorials/tutorial-lesson-06.html#lesson-6:-crontrigger)

I would like your advice and guidance to implement this in the library as a parsing spec.

**Comment by llonchj** [comment]
@robfig any thoughts?

**Comment by robfig** [comment]
It supports Seconds, but not Year. On the v3 branch, construct cron with:I don't see the value of Year.

**Comment by robfig** [comment]
Closing as I have no plans to implement year, and Seconds is already available. That seems ok to me.

**Comment by lvjing2** [comment]
I am curious about why not going to support year, I think this is also useful in some case.

**Comment by tomqwpl** [comment]
Supporting a year means you can express a single point in time, so "run once", so can be very useful.
