### ISSUE TITLE
Support for more special characters (#, W, L)

### ISSUE THREAD

**Issue by pjebs** [robfig/cron#165]
Will  special characters such as `#`, `W` and `L` be supported?

**Comment by pjebs** [comment]
https://github.com/dragonmantank/cron-expression/blob/master/src/Cron/DayOfMonthField.php

https://github.com/dragonmantank/cron-expression/blob/master/src/Cron/DayOfWeekField.php

**Comment by robfig** [comment]
I have not thought about implementing those features, so I can't say how difficult they might be. I am open to a pull request as long as it fits with the surrounding code, comes with comprehensive tests, and updates the documentation
