### ISSUE TITLE
[Support] @daily+ specified time

### ISSUE THREAD

**Issue by dravenk** [robfig/cron#168]
How to write c.AddFunc in this cron job? 
` Every evening at 20 o 'clock `

**Comment by dravenk** [comment]
"0 * 20 * * *"  
second/minute/hour/day/month/year

**Comment by NickyMateev** [comment]
@dravenk It should be so "* * 20 * * *".

What your cron expression does is actually execute the job every minute at 20PM each day.

**Comment by dravenk** [comment]
@NickyMateev 
Your information is really important to me. Thank you very much!
