### ISSUE TITLE
AddJob, AddFunc redundant?

### ISSUE THREAD

**Issue by mcandre** [robfig/cron#176]
Looks like users can register tasks as either pure Go functions or as Job interface implementations, which is kind of redundant. What are your thoughts about deprecating one of these?

**Comment by mewa** [comment]
A `Job` can contain more information about its execution, so it's definitely more useful.

However, deprecating `AddFunc` would make it less convenient to use in the most basic case (which is also probably the most prevalent).

**Comment by robfig** [comment]
Yeah, I guess Go usually errs on the side of not providing sugar like that, assuming that wrapping a func in a Job is easy enough. 

But also, there is another feature request for making it `cron.AddEntry` where an Entry contains the schedule and the Job. I think we can agree that would be too inconvenient?

e.g.
```
cron.AddEntry(cron.ParseEntry("0 0 * * * *", cron.JobFunc(func() { ... })) 
```

**Comment by robfig** [comment]
Thinking about this a bit, if I were writing this again, I would probably agree with @mcandre and not include the sugar, since it's such an easy thing to wrap with `cron.JobFunc`. But it doesn't seem worth removing the function now that it's been out there for years. Ah well, legacy code!
