### ISSUE TITLE
Feature: Name and remove jobs

### ISSUE THREAD

**Issue by mcandre** [robfig/cron#177]
For more dynamic workflows, would be really helpful to be able to assign names to jobs, and to delete named jobs.

As a workaround, one could manage a map of names to individual `cron.Cron` instances, and manually Start() and Stop() each Cron instance as needed.

**Comment by robfig** [comment]
This is supported on the v2 branch, and I'm trying to find the best way to support this for v3.

**Comment by robfig** [comment]
Please let me know if the current approach on v2 or v3 has any problems for you.
