### ISSUE TITLE
Enhancement: Clarify second vs. minute precision

### ISSUE THREAD

**Issue by mcandre** [robfig/cron#179]
Most cron implementations feature minute precision, not second precision. There are a lot of cron spec strings that would be nice to copy to a Go application using robfig/cron. However, robfig/cron currently behaves weirdly when the second value is missing from the cron spec string.

Instead of treating missing second values as the zero second (how minute-precision cron implementations behave), robfig/cron treats this as every (`*`) second. This is likely not what the user wants.

Please adjust the cron spec parser so that when seconds are omitted, they default to the zero second.

**Comment by hdpinto** [comment]
This.

It's baffling that one could call a package `cron` and then go right ahead and not use the standard `cron` syntax of `m h d m y w`. This actually caused some significant confusion during code review with some more experienced linux developers.

**Comment by robfig** [comment]
Yes, I agree that was an unfortunate decision. As a Java developer, I was most familiar with Quartz Scheduler which has that format, and I didn't realize that it conflicted heavily with most expectations. Anyway, I'm aiming to correct this in the v3 release and make minute granularity the default. Sorry for the confusion.
