### ISSUE TITLE
Enhancement: UTC

### ISSUE THREAD

**Issue by mcandre** [robfig/cron#180]
As an engineer managing multi-region deployments, it would be more consistent for robfig/cron to:

* Default to UTC timezone when the cron spec schedule is not explicitly associated with any particular timezone.
* Allow custom timezones to be specified, for managing more complex deployments.

So that we have a more robust, well specified scheduling system, rather than relying on A) local time and B) a consistent local timezone and C) identical timezone configurations across clusters of servers.

**Comment by robfig** [comment]
I might be missing something, but if you deploy your software on servers using UTC as their timezone, the specs will be interpreted in UTC as well, unless they have an explicit override. Is that what you're seeing?

**Comment by robfig** [comment]
Since I'm pretty confident that it works as written in my last comment, and that seems like it addresses your use case, I'm going to close this as not actionable. Feel free to reopen with additional information about what specifically you would like to see different.

**Comment by mcandre** [comment]
For local development, it gets hairy expecting developers to remember that robfig/cron configurations are implicitly local time. Servers may be UTC, but developer machines are *rarely* ever UTC, and surprises happen when you copy and paste server configuration to developer machines.

Please add an option to specify the timezone.
