### ISSUE TITLE
Expression not working

### ISSUE THREAD

**Issue by fallais** [robfig/cron#186]
Hello,

I had an issue with `* 30 14 * * *`, it was flooding every second. I understood that it was because of the first star. So I changed it to `0 30 14 * * *`. But it is not working.

I want my job to execute everyday at **14h30**.

What am I missing please.. ?

**Comment by armmydev** [comment]
I got the same issue.

**Comment by evo3cx** [comment]
maybe this statement can help you.

```
Implementation
Cron entries are stored in an array, sorted by their next activation time. Cron sleeps until the next job is due to be run.

Upon waking:

- it runs each entry that is active on that second
- it calculates the next run times for the jobs that were run
- it re-sorts the array of entries by next activation time.
- it goes to sleep until the soonest job.
```

**Comment by robfig** [comment]
I believe that this spec is correct:
```
0 30 14 * * *
```

Note that it uses the local time zone of the machine. If you run it in Docker, that is probably UTC which might explain why you didn't see it run. You can specify the time zone you mean explicitly if you wish:

```
TZ=America/New_York 0 30 14 * * *
```
