### ISSUE TITLE
how to update scheduled tasks

### ISSUE THREAD

**Issue by zhanglh1024** [robfig/cron#187]

**Comment by zhanglh1024** [comment]
I don't know how to update the scheduled tasks when later task didn't finish.

**Comment by evo3cx** [comment]
you can save failed to task to the database and make the other task to check if prev task succeed

**Comment by robfig** [comment]
Sorry, this ticket doesn't have enough information for me to help. Please follow the guidelines here for questions:
https://github.com/golang/go/wiki/How-to-ask-for-help#asking-questions

This library is about scheduling things to run; it is out of scope to handle retry of failed tasks. Feel free to reopen with more information.
