### ISSUE TITLE
Is version 3 a default/better version?

### ISSUE THREAD

**Issue by sirius1024** [robfig/cron#189]
Master or V3 branch makes me confused, which is the correct, please?

**Comment by robfig** [comment]
Yes, v3 currently contains a merge of v1 and v2 as well as additional bug fixes. I plan to resolve all outstanding issues / feature requests through development on v3. It would be a great help if you try it out (especially using Go Modules) and let me know if anything doesn't work as expected. Thanks!

**Comment by sirius1024** [comment]
@robfig Ahh...For now I'm working with the master branch and go modules and works fine at production environment.

If needs a test of V3, I'm glad to do it with my own project.
