### ISSUE TITLE
socket

### ISSUE THREAD

**Issue by cookiefour** [robfig/cron#190]
c := cron.New()
c.AddFunc("", func() {
	//  有redis操作
})
c.Start()
select {}

这样启动定时，任务里有redis操作，导致linux下redis连接生成的socket无法释放，这是为什么

**Comment by ytinirt** [comment]
@cookiefour 【redis操作】能否具体点。。

**Comment by robfig** [comment]
Google translate makes it sound like this question is about connection management with Redis. Cron does nothing but run your function, so I don't believe it has anything to do with that.
