### ISSUE TITLE
start of multiple simultaneous goroutines

### ISSUE THREAD

**Issue by Shukla-Ankur** [robfig/cron#191]
In my code, I try to connect to MySQL DB (within a cron function). In cases when this connection establishing takes time, cron starts running the registered function in another goroutine. 
Is there any way to ensure that if a gorotuine has already been started, do not start a new one unless the previous one finishes?

**Comment by ytinirt** [comment]
@Shukla-Ankur   you can achieve that with Mutex or Channel simply in you code.

**Comment by robfig** [comment]
You can use the new SkipIfAlreadyRunning JobWrapper in v3. Please have a look and let me know if you have any problems.
