### ISSUE TITLE
Application does not stop on Panic in registered function

### ISSUE THREAD

**Issue by Shukla-Ankur** [robfig/cron#192]
I'm using ```AddFunc``` for one of my applications, which actually is a gRPC server. When the registered function panics, the application does not stop, just the goroutine which was running the function, and then the function is run as scheduled with cron.
Shouldn't the behavior of panic be honored? if the application intends to not close, then it would send an error. Why is panic being suppressed here?

**Comment by CybotTM** [comment]
Great issue! We've implemented job dependencies in [Ofelia](https://github.com/netresearch/ofelia) (a Docker job scheduler built on go-cron) and would love to see this natively supported.

Our `WorkflowOrchestrator` implementation supports:

1. **DAG-based dependencies** - Jobs can declare dependencies on other jobs
2. **Circular dependency detection** - Prevents infinite loops at registration time
3. **OnSuccess/OnFailure triggers** - Conditional execution based on parent job outcome
4. **Parallel execution** - Independent jobs in the DAG run concurrently

Key design decisions we made:
- Dependencies are validated at scheduler start (fail-fast for misconfiguration)
- Dependent jobs are triggered immediately after parent completes, not on next cron tick
- Context propagation allows cancellation to cascade through the workflow

Example configuration in our INI format:
```ini
[job-run "backup-db"]
schedule = @daily
command = pg_dump ...

[job-run "upload-backup"]
on-success = backup-db
command = s3 cp ...

[job-run "notify-failure"]
on-failure = backup-db
command = curl -X POST ...
```

We'd be happy to contribute a PR for a simpler version as a go-cron extension. Perhaps something like:

```go
c.AddJob("backup", backupSpec, backupJob)
c.AddJob("upload", cron.OnSuccess("backup"), uploadJob)
c.AddJob("notify", cron.OnFailure("backup"), notifyJob)
```

Would this direction align with what you're envisioning?
