### ISSUE TITLE
Go fails to pull revisions due to wrong tag name format

### ISSUE THREAD

**Issue by Shukla-Ankur** [robfig/cron#196]
Could you please rename the tags to v1.1.0 etc because go treats v1.1 as invalid (essentially without a build number)?

I get the following error

go: errors parsing go.mod:
/Users/as/mt-store-doc-service/go.mod:15: invalid module version "v1.1": no matching versions for query "v1.1"

I tried with both v1.1 and 1.1 and it fails with same error every time.

**Comment by robfig** [comment]
Done, let me know if you have any other problems!
