### ISSUE TITLE
Do we have a rough date when v3 is going to be released?

### ISSUE THREAD

**Issue by vankofalcon** [robfig/cron#199]

**Comment by robfig** [comment]
I think you can actually use the v3 branch today. It is strictly better than either v1 or v2 -- roughly speaking, it has more features than v1 and more fixes than v2. I've already tagged v3.0.0-rc1, but I will have time next month to finish the features I wanted to add to address other issues, at which point I was going to tag v3.0.0 final. But I don't foresee any breaking changes at this time, and I do not know of any issues with the current version.

**Comment by vankofalcon** [comment]
Thanks @robfig
