### ISSUE TITLE
Timeout

### ISSUE THREAD

**Issue by fallais** [robfig/cron#200]
Hello,

is there any chance that it is normal that my func are being stopped exactly after one hour ?
Thanks a lot.

**Comment by robfig** [comment]
cron starts your job in its own goroutine and does not interfere with it in any way. My only guess is if your func is scheduled to run every hour, and the second run interrupts the first due to some shared resource. Without seeing the code, I can't offer any other advice.

**Comment by fallais** [comment]
Actually, it is scheduled every 3 hours, but the function is dying after 1 hour exactly but I do not understand why, this is crazy, no error, nothing..

**Comment by robfig** [comment]
Sorry, I don't have the information to help you diagnose that, but there is no mechanism in the cron library that could cause it. Unless you have some other idea, I don't see the connection with this library. I hope you solve it!
