### ISSUE TITLE
Return concrete SpecSchedule type from calls to Parse

### ISSUE THREAD

**Issue by lthibault** [robfig/cron#201]
It appears that all Parse functions return a concrete `*SpecSchedule` under the hood.  It would be useful to return the concrete type instead of the interface.

Not only is this more idiomatic Go, it is useful in cases where users wish to e.g. save a `SpecSchedule` to a database.

**Comment by robfig** [comment]
What is the use case for saving a SpecSchedule instead of the string (the cron spec)? A spec should result in the same SpecSchedule whenever it's parsed, and the spec is much more readable and easier to serialize for storage.

**Comment by lthibault** [comment]
Cron strings aren’t all that standard; implementations can vary a bit (e.g. what does the empty string mean?  Some implementations run the job continuously, others never).

The parsed object is unambiguous.

— 
Louis Thibault
CEO, Sentimens Research Group

**Comment by robfig** [comment]
Oh, `Parse()` does not always return a SpecSchedule. If you pass `@every 1h30m`, it returns a ConstantDelaySchedule.

**Comment by lthibault** [comment]
Ah, fair point.  Please disregard this issue, then.

**Comment by robfig** [comment]
👍
