### ISSUE TITLE
Logger interface

### ISSUE THREAD

**Issue by tamalsaha** [robfig/cron#202]
Instead of introducing a custom logger interface, please consider  https://github.com/go-logr/logr

**Comment by robfig** [comment]
It doesn't seem like logr has any traction, and it has a more complicated interface than the single Printf method, which would make adapting existing logger implementations to it more more difficult.

**Comment by tamalsaha** [comment]
It is being used in the Kubernetes project.
https://github.com/kubernetes-sigs/controller-runtime/search?q=logr&unscoped_q=logr

But I understand your point.

**Comment by robfig** [comment]
I didn't realize it was used in Kubernetes. Like you, I wish Go had a widely-adopted Logger interface. Reading more, it seems like they have done a good job thinking it through.

Here's what it would look like for cron. What do you think?
https://github.com/robfig/cron/commit/da975fa59e7bcd7b7d09838ac12a153073f813fc

**Comment by mwei0210** [comment]
Wouldn't work with https://github.com/uber-go/zap

**Comment by tamalsaha** [comment]
@mwei0210 , you can use https://github.com/go-logr/zapr

**Comment by tamalsaha** [comment]
Thanks for considering logr. Your pr looks good to me @robfig !

**Comment by robfig** [comment]
I think the resulting code works well, so I've pushed this to the v3 branch. I also tagged a new release. Please give it a go and let me know any feedback. Thanks
