### ISSUE TITLE
golang process existed, but cpu usage rate is 0, and it doesn't work.  this phenomenon occur on my mac and aliyun ecs

### ISSUE THREAD

**Issue by fengbenming** [robfig/cron#204]

**Comment by robfig** [comment]
Can you please see if it happens with the latest commit on the v3 branch? If so, please post your program

**Comment by fengbenming** [comment]
I have change to v3 branch. this problem is difficult to reoccur, so it need some time to occur.  as this problem happen, there's not any error info or business log  printed, like the process is been cut suddenly, but is not existed.  some other go program in the same server can work ok.

**Comment by robfig** [comment]
Well, please let me know if you see anything else. Also, if you activate verbose logging as described in the readme, it will provide more information to help debug any future problems. Thanks
