### ISSUE TITLE
TestNonLocalTimezone / cron_test.go seems to be racy, fail intermittently

### ISSUE THREAD

**Issue by goodwinos** [robfig/cron#205]
Some of the tests in cron_test.go seem to fail intermittently due to race conditions. The test schedules a job for 1 second and 2 seconds in the future (in absolute time), waits 2 seconds and checks it's been called twice, which sometimes doesn't occur reliably. For further details, see
https://bugzilla.redhat.com/show_bug.cgi?id=1714432#c7

**Comment by robfig** [comment]
I'll have a look at making that less flaky. Thanks for the report

**Comment by robfig** [comment]
I was able to reproduce it using `go test -count=100` and combined with some extra logging solved the problem. This should be fixed at head. I'm planning on tagging another release today or this weekend that includes it. Thanks
