### ISSUE TITLE
Timer reference to 'now' not reset on delete

### ISSUE THREAD

**Issue by ddelger** [robfig/cron#206]
In the internal loop of the run method the local variable `now` is updated when a new entry is added but not deleted.

https://github.com/robfig/cron/blob/v3/cron.go#L280

This results in the timer getting reset based an on outdated reference to now. Causing the trigger to later than specified.

https://github.com/robfig/cron/blob/v3/cron.go#L244

**Comment by robfig** [comment]
Thank you for the bug report! I agree that looks incorrect. I'll work on adding a test to catch it and then fix the bug.

**Comment by robfig** [comment]
I was able to reproduce and fix the bug. Thank you!

**Comment by ddelger** [comment]
Great thanks! 

I also just noticed a pr to add update functionality. I would imagine the same issue would occur here as well.

https://github.com/robfig/cron/pull/183/files
