### ISSUE TITLE
Request to get a release of robfig/cron

### ISSUE THREAD

**Issue by tariq1890** [robfig/cron#207]
Hello! Thanks for this repository. I see that the release candidate was published more than 2 months ago. Would it be possible get a release cut from the master?

**Comment by robfig** [comment]
Yep, I hope to have that out soon. I wanted to merge the logr branch prior to that, which includes some important new functionality. I believe it's code complete, and I just want to review it again.

**Comment by robfig** [comment]
Release is tagged! v3.0.0. I also changed the default branch so that the v3 README appears when you visit the front page of this repo. Please have a look and let me know if you see any issues!
