### ISSUE TITLE
alarm.AddFunc("0 50 5 * * *", func() {}  does not work under the v3 branch, is't a problem?

### ISSUE THREAD

**Issue by fengbenming** [robfig/cron#208]

**Comment by robfig** [comment]
When posting a bug report, please include the program you ran, what you expected to see, and what you actually saw. I can't do anything with this. Also, note that the cron specs have different meaning between the versions -- v1 was initially released with seconds in the first column. That is not part of standard cron, so v2 and v3 have minutes in the first column.

**Comment by robfig** [comment]
Oh yeah, your spec is incorrect for v3. Remove the leading "0 "

**Comment by fengbenming** [comment]
> Oh yeah, your spec is incorrect for v3. Remove the leading "0 "

thanks very much. I was testing the issue #204 under v3 branch, so I meet the new problem
