### ISSUE TITLE
Please provide NewStandardParser() helper

### ISSUE THREAD

**Issue by tamalsaha** [robfig/cron#210]
We used to use `cron.Parse()` to validate cron expressions received from user. `NewStandardParser()` will be useful for us.

**Comment by robfig** [comment]
I believe that already exists: `cron.ParseStandard`. Unless you need the concrete `cron.Parser` instance for some reason?

**Comment by tamalsaha** [comment]
I did not notice `cron.ParseStandard`. That will do the job. Thanks!
