### ISSUE TITLE
Please Tell Me Why

### ISSUE THREAD

**Issue by fannatical-gopher** [robfig/cron#213]
I am very confused about that why I go get this pkg in my ci,the branch which be download is v3 branch not the master,my cronjob works did't work for 3 days,the most important thing is i don't know why.so could you please give me the reason about that,why!!!!!!!

**Comment by robfig** [comment]
Oh, I changed Github's "default branch" to v3 so that visitors would not see an old version by default. I didn't know that would change the behavior of "go get"

**Comment by fannatical-gopher** [comment]
so you may change master into default branch. If anyone wants to  use v3 they can use glide and lock the version of this pkg

**Comment by pjo256** [comment]
+1, this is appears to be causing build issues in https://github.com/kubeflow/pipelines/issues/1620. An alternative approach would be to merge your `v3` branch into `master`, so new users see your most recent release while others can pin versions to the next major release when they're ready to migrate using tags.

**Comment by robfig** [comment]
Merging v3 into master would not fix the breakages, because it's not backwards compatible. I think the source of the issues is that everyone who's not pinning a version is now getting v3 instead of v1. 

On the other hand, if I make master the default branch again, there would be no way for developers on v3 to see the godoc. Hrm, what a pickle. Let me see...

**Comment by pjo256** [comment]
Interestingly, that project pins to a commit tagged with `v1` - `b41be1df6967` 🤔 . I'm not too familiar with godoc, but would https://godoc.org/gopkg.in/robfig/cron.v3 work regardless of the default branch (as opposed to https://godoc.org/github.com/robfig/cron)?

**Comment by phuslu** [comment]
Oh No, change back also make our projects need reinstate old codes.

very very dispointed.

**Comment by robfig** [comment]
I requested community input here:
https://groups.google.com/forum/m/#!topic/golang-nuts/elraGIpy52Q

Perhaps the best thing is to have folks just deal with whatever breakage is caused by changing the default branch rather than the long-term cost of leaving default branch on v1.

**Comment by deviantony** [comment]
@robfig did you rollback your changes and make master default again?

**Comment by phuslu** [comment]
I suggest that use another(but commonly) solution.

Keep https://github.com/robfig/cron stay old master branch.

Then create another projects  https://github.com/go-cron/cron and switch to latest interfaces.

And finally, tell people migration to go-cron/cron in robfig/cron README.

**Comment by juanpabloaj** [comment]
@fannatical-gopher a solution could use go modules and pin the version 1.x, to your go.mod add a line like this

```
require (
  ...
  github.com/robfig/cron v1.2.0
  ...
)
```

**Comment by fannatical-gopher** [comment]
@juanpabloaj well well it seems that robfig have setted v1 into default branch but thanks to your advice,it surely does work

**Comment by robfig** [comment]
Based on the feedback I got, it seems like the best way forward is to stick with changing the default branch to v3, which I've just done. If you rely on getting a specific version, then please use Go modules for that purpose as described above. Thanks, and sorry for any issues this causes, but after a period of updating, this will be better for everyone.

**Comment by robfig** [comment]
I scanned the list of packages that import this one on godoc and clicked into the ones with names I recognized.

Looks like these projects have go.mod files so wouldn't be affected:
https://github.com/drone/drone
https://github.com/gaia-pipeline/gaia

These use dep
https://github.com/GoogleCloudPlatform/spark-on-k8s-operator
https://github.com/uber/cadence

Bazel(?)
https://github.com/kubernetes/kubernetes

and I opened a couple issues where I didn't see version pinning (linked above)

**Comment by qienhuang** [comment]
I need the cron.Remove() function from V3, after I upgraded the package from master to V3 by
go get gopkg.in/robfig/cron.v3
import "gopkg.in/robfig/cron.v3"
the crons stop working. I figured it out the difference:
cron.AddFunc("* * * * * *", func() {
	fmt.Println()
})
The AddFunc() in master supports 6 fields of spec, the first field is second.
The AddFunc() in V3 support 5 fields of spec, the first is minutes.

**Comment by robfig** [comment]
Sorry you had some trouble. I documented the upgrade instructions here:
https://github.com/robfig/cron/blob/v3/README.md

"""
It is backwards incompatible with both v1 and v2. These updates are required:

- The v1 branch accepted an optional seconds field at the beginning of the cron spec. This is non-standard and has led to a lot of confusion. The new default parser conforms to the standard as described by the Cron wikipedia page.

    UPDATING: To retain the old behavior, construct your Cron with a custom parser:

"""

**Comment by robfig** [comment]
Any thoughts on which way to go?
(1) update master to point to v3, or 
(2) change the default branch to be v3 ?

**Comment by robfig** [comment]
Well, I think the status quo is worse than either of those two options. I'm going to go with (1) and update master to point to HEAD. That seems like the most standard approach and should work for anyone who has vendored, pinned a revision, or uses Go modules.
