### ISSUE TITLE
Question on high CPU usage

### ISSUE THREAD

**Issue by zluo01** [robfig/cron#217]
I had a cron job running inside a docker container, but the cpu usage is really high.
<img width="796" alt="image" src="https://user-images.githubusercontent.com/12102011/62393944-5c6a3500-b531-11e9-995e-2a00bb5b9565.png">
My code looks like this
```
func main() {
	c := cron.New()
	if err := c.AddFunc("@midnight", func() {
		log.Printf("Start crawling latest data on : %s", time.Now())
		start := time.Now()
		dailyUpdate(10000)
		elapsed := time.Since(start)
		log.Printf("%s took %s\n", "DailyUpdate", elapsed)
	}); err != nil {
		log.Fatal(err.Error())
	}
	log.Println("Start the crawler")
	for {
		c.Start()
	}
}
```
I want to ask if my way of using it is wrong. Thank you

**Comment by robfig** [comment]
Yes, replace 

```
for {
   c.Start()
}
```

with 
```
c.Run()
```
