### ISSUE TITLE
cron.Parse(<string>) timezone

### ISSUE THREAD

**Issue by pjebs** [robfig/cron#218]
I was wondering how I could set the timezone for `cron.Parse(<string>)`?

The docs state it uses machine timezone.

**Comment by pjebs** [comment]
My use case is essentially what you addressed here: https://github.com/robfig/cron/issues/142 (generate the next N times of cron spec from an arbitrary time t).

**Comment by pjebs** [comment]
The only place I can see the ability to config timezone is `func NewWithLocation(location *time.Location) *Cron`. No idea how to generate next N times out of that.

**Comment by robfig** [comment]
To specify timezone, prefix the cron spec with CRON_TZ= or TZ=. To generate the next N times, then you'd have to call cron.Parse to get a cron.Schedule and write a loop that repeatedly calls Next with the last time returned.

**Comment by pjebs** [comment]
How about using the technique you mentioned in #142 but with the provided t argument having a location set instead of UTC? Would that work?

**Comment by pjebs** [comment]
( I used go get so it appears I am on master)

**Comment by robfig** [comment]
Yeah, that's exactly the sort of thing I mean. Note that there are two different time zones in play -- the cron spec has one, and the time zone of the scheduler has one. If you want to do everything in the same local time zone, you would need to set both, I believe.
