### ISSUE TITLE
It's not working

### ISSUE THREAD

**Issue by AjithKumar-Raj** [robfig/cron#223]
hi @robfig,

I just created a sample program but that's not working.

```
package main
import (
	"fmt"
	"github.com/robfig/cron"
)
func main() {
	c := cron.New()
	c.AddFunc("* * * * * *", func() { fmt.Println("I'm robfig/cron") })
	c.Start()
}
```
Can you help me to understand what wrong in this?

**Comment by robfig** [comment]
`c.Start()` starts the scheduler in its own goroutine and returns immediately. Then the program exits. Use `c.Run()` if you want to run the scheduler in the current goroutine, which blocks until `Stop()` is invoked, or do something else with the goroutine to prevent the program from exiting.

**Comment by AjithKumar-Raj** [comment]
thanks @robfig
