### ISSUE TITLE
Translate cron expression into actual human readable text

### ISSUE THREAD

**Issue by gotjosh** [robfig/cron#229]
I'm currently in need of attempting to parse a Cron expression into an actual human-readable format that's not a date - a la [cronex](https://github.com/alpinweis/cronex).

e.g.
```
*/5 15 * * 1-5
Every 5 minutes, at 3:00 PM, Monday through Friday

0 0/30 8-9 5,20 * ?
Every 30 minutes, between 8:00 AM and 9:59 AM, on day 5 and 20 of the month
```

Is this something you would like to see as part of `cron`? If so, I'd be happy to contribute.

**Comment by robfig** [comment]
I think having that functionality as a separate module would be good. It seems like a big increase in scope, and I already feel like I don't have the time to maintain this module effectively. If you do make a module, I'd be happy to link from it from the documentation here. Let me know, and good luck!
