### ISSUE TITLE
Cron not worked as doc specified

### ISSUE THREAD

**Issue by HackToday** [robfig/cron#230]
Follow https://godoc.org/github.com/robfig/cron#Cron.AddFunc

this example：

```
c := cron.New()
c.AddFunc("0 30 * * * *", func() { fmt.Println("Every hour on the half hour") })
c.Start()
```

Found it complain as following:

 expected exactly 5 fields, found 6: [0 30 * * * *]

**Comment by robfig** [comment]
That was because of version issues -- the documentation you quote is from v1, but the code you're getting is probably v3. 

I've pushed v3 to master so everything should be consistent now. Please have a look. Sorry for the hassle.
