### ISSUE TITLE
go get -u -v gopkg.in/robfig/cron.v3

### ISSUE THREAD

**Issue by idersan** [robfig/cron#232]
>go get -u -v gopkg.in/robfig/cron.v3
Fetching https://gopkg.in/robfig/cron.v3?go-get=1
Parsing meta tags from https://gopkg.in/robfig/cron.v3?go-get=1 (status code 200)
get "gopkg.in/robfig/cron.v3": found meta tag get.metaImport{Prefix:"gopkg.in/robfig/cron.v3", VCS:"git", RepoRoot:"http
s://gopkg.in/robfig/cron.v3"} at https://gopkg.in/robfig/cron.v3?go-get=1
go: gopkg.in/robfig/cron.v3@v3.0.0: go.mod has non-....v3 module path "github.com/robfig/cron/v3" at revision v3.0.0
go get: error loading module requirements

**Comment by robfig** [comment]
Since it uses Go modules, I believe it will work if you follow this:

"""
Import it in your program as:

    import "github.com/robfig/cron/v3"
"""

Let me know if not!
