### ISSUE TITLE
cron job with localization did not work

### ISSUE THREAD

**Issue by krutztq** [robfig/cron#235]
Using v3. (https://godoc.org/github.com/robfig/cron#v3)
I have a system which runs in UTC, but I want to trigger cron jobs for different timezones.
I tried to start 2 jobs with localization, but it did not work.

Here is the code:
	cronContext := cron.New()
	cronContext.AddFunc("CRON_TZ=Asia/Kamchatka 0 0 * * *", func() {
		// round timestampMidnight to one day
		log.Debug("Test 1: UTC =", time.Now().Unix())
	})
	cronContext.Start()

	loc, err := time.LoadLocation("Asia/Kamchatka ")
	if err != nil {
		loc, _ = time.LoadLocation("UTC")
		log.Info("Cannot read timezone, set UTC location for data aggregation")
	}
	cronContext2 := cron.New(cron.WithLocation(loc))
	cronContext.AddFunc("0 0 * * *", func() {
		// round timestampMidnight to one day
		log.Debug("Test 2: UTC =", time.Now().Unix())
	})
	cronContext2.Start()

I ran the code 11:55 am UTC (23:55 in Kamchatka) and expected to see both log messages at 12:00. Nothing happened. Can you help me?

greetings

**Comment by aranda-adapptor** [comment]
I'm experiencing the same issue. I've tried the `"CRON_TZ=..."` prefix for the jobs and `cron.New(cron.WithLocation(...))` approach but each time it seems to use UTC regardless.

**Comment by robfig** [comment]
This is surprising, because there are unit tests verifying the behavior. Note that your code snippet has a typo and uses `cronContext` instead of `cronContext2` for the second instance. 

Can you post a gist of a full program that demonstrates the issue, or (even better) a test case that fails? 

Thank you!

**Comment by aranda-adapptor** [comment]
I have it working now with `CRON_TZ` prefix, however the `cron.WithLocation` approach did not work for me. I don't have a working example but the following code seemed to work locally when my computer's time zone matched the requested zone, however once deployed to a server with UTC clock it seemed to ignore the time zone.

```
Cron = cron.New(cron.WithLocation(time.FixedZone("Australia/Perth", 0)))
// Test 1 minute interval in a specific range of hours to check the time zone works
Cron.AddFunc("0-59/1 4-20 * * *", func() { fmt.Println(time.Now(), "Hello") })
```

And this works even when running in a UTC environment:

```
Cron = cron.New()
// Test 1 minute interval in a specific range of hours to check the time zone works
Cron.AddFunc("CRON_TZ=Australia/Perth 0-59/1 4-20 * * *", func() { fmt.Println(time.Now(), "Hello") })
```

**Comment by krutztq** [comment]
Thanks for your help, it works now!
