### ISSUE TITLE
Parse a whole line of crontab

### ISSUE THREAD

**Issue by kleijnweb** [robfig/cron#238]
As far as I know, there's currently no way to parse a full line of crontab using `robfig/cron`, that is to say, including the script.

This is because the parser will only parse the schedule and return an error if it finds too many fields or a malformed DOW.

I realize this is probably not the most common use case, for those of like myself who are looking parse a whole line from a standard crontab, this is quite the PITA.

It would be great if we would be able to do something like `NewParser(Minute| Dom | Month | DowOptional | Script)`.

**Comment by robfig** [comment]
Isn't it relatively straightforward to peel the script off prior to handing the crontab to this package?

**Comment by kleijnweb** [comment]
Well you would have "parse" (however you want to do it) the input to separate the script from the schedule, which would be either pretty adhoc, or, very similar to what the parser in this package already does. Just seems like the parser would be the right place for it.

Alternatively, the parser could only take from the input string that it knows how to deal with, and leave the remainder for the client code. As opposed to failing on extra input.

**Comment by robfig** [comment]
Changing the parser to have that behavior would mean that it could not return error messages if too many fields are provided by accident. I see that as a useful functionality. Sorry!
