### ISSUE TITLE
Unable to parse a range (strconv.Atoi error)

### ISSUE THREAD

**Issue by danielma82** [robfig/cron#241]
I am getting this error
> failed to parse int from 1-4: strconv.Atoi: parsing "1-4": invalid syntax

from the cron string
"*/1-4 * * * *"

Please let me know if this is just me being stupid or a bug. Because afaik ranges should be supported as a hyphen is an accepted character.

**Comment by robfig** [comment]
I believe ranges are not expected as the divisor, but they definitely work prior to the slash. The error handling could probably be better. What schedule are you trying to create?  

Refer here to Slash usage:
https://en.wikipedia.org/wiki/Cron

**Comment by danielma82** [comment]
I'm trying to create this schedule here. 
https://cronexpressiondescriptor.azurewebsites.net/?expression=*%2F1-4+*+*+*+*&locale=en

**Comment by robfig** [comment]
That schedule doesn't make sense to me -- what does running a job every 1-4 minutes mean? 

To take the first element in the range: let's say you run a job every 1 minute. How does the 2-4 portion of the range change that schedule?

**Comment by danielma82** [comment]
Sorry for leaving this open. I believe I was trying to have a job run at intervals of 1,2,3, or 4 minutes. That is my best guess. Not sure if cron even supports such a thing?
I've been (possibly incorrectly) relying on this website https://cronexpressiondescriptor.azurewebsites.net/?expression=*%2F1-4+*+*+*+*&locale=en
for cron descriptions.

Either way I have no need to do this anymore and you can consider this a user error. Thanks for your time.
