### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by zhonghua1219** [robfig/cron#245]
The memory always increases since the program start , I find that this is cased by time.NewTimer  in the cron.go file on line 248.
Any one has some method to resolve it ?

**Comment by felix0080** [comment]
Maybe you should provide more information, maybe it's because you used it incorrectly.

**Comment by robfig** [comment]
If you'd like to provide more information, please feel free to reopen.

**Comment by Raiden1974** [comment]
> Maybe you should provide more information, maybe it's because you used it incorrectly.

You use simple call to stop timer - timer.Stop() it periodically cause memory leaks. Use:
 if !timer.Stop() {
  <-timer.C
}

**Comment by zhonghua1219** [comment]
你好，你的邮件我已经收到！！
