### ISSUE TITLE
what happends when job run time exceeds interval decalred by @every

### ISSUE THREAD

**Issue by saintAsmita** [robfig/cron#247]
if I decalre job using @every 1s, but every job need 5s to run.

can support fixed-delay schedule?

**Comment by robfig** [comment]
Cron will run your job on the schedule you give it, nothing more or less. There is a new feature to delay the start of an execution if the previous one is still running:
https://godoc.org/github.com/robfig/cron#DelayIfStillRunning

.. but it does not support a fixed delay schedule.
