### ISSUE TITLE
fork/exec sh_script :cannot allocate memory

### ISSUE THREAD

**Issue by wtx626** [robfig/cron#248]
when I exec.Commend(sh_script) in crontab, after a while , it will be down.

> fork/exec sh_script :cannot allocate memory

I do not know why ,  can anyone give me help?

**Comment by robfig** [comment]
This question is not particularly related to this library, and you haven't given much information to help you (for example, a program that reproduces the problem). My only guess is that you are not closing some resource associated with each execution. 

Closing as "not enough information"
