### ISSUE TITLE
Cron#Stop should block until all jobs are done running

### ISSUE THREAD

**Issue by edaniels** [robfig/cron#249]
Right now `go c.runWithRecovery(e.Job)` kicks off jobs that may end up running after the cron is stopped which makes it hard to know in consumer code when you can safely continue on. For example, the job might be something that sends on a channel that we close when `Stop` returns which creates a race condition.

**Comment by robfig** [comment]
Stop() returns a context that completes when the last job is done running. It sounds like that will handle your use case, but please reopen and let me know if I've missed something. Cheers
https://godoc.org/github.com/robfig/cron#Cron.Stop

**Comment by edaniels** [comment]
Ah duh! Thanks!

**Comment by optimistic9527** [comment]
@robfig iIf a task runs for a long time, the program can‘t exit. I want to know why the signal notification method was not used at that time.
