### ISSUE TITLE
Cron not doing anything

### ISSUE THREAD

**Issue by mDomingues** [robfig/cron#25]
Hi @robfig,

I set a cron for some tasks but they weren't being executed. In order to understand I did this:

func main() {
	c := cron.New()
	c.AddFunc("@every 10s", func() { log.Println("Every sec") })
	c.Start()
}

Go run this file and it doesn't print the message. What am I missing ?

**Comment by andreasen** [comment]
I believe it is because your main function exits right after you have called c.Start().

You need something to keep it alive, example below with a loop:

```go
package main

import (
	"github.com/robfig/cron"
	"log"
)

func main() {
	c := cron.New()
	c.AddFunc("@every 1s", func() { log.Println("Every sec") })
	c.Start()
	for {
		select {}
	}
}
```

**Comment by robfig** [comment]
That's correct.. we could potentially expose a cron.Run() function that runs it in the current goroutine to service that use case .. in the meantime just be sure to do something that blocks without spinning.  select {}  works well for that, even without the loop:

```go
  c.Start()
  select{}
```

**Comment by mDomingues** [comment]
That would be a nice feature.
Many thanks. It was it :)
