### ISSUE TITLE
Looks like I can not use range to add jobs

### ISSUE THREAD

**Issue by lixiangzzz2017** [robfig/cron#252]
package main

import (
	"fmt"
	"github.com/robfig/cron"
	"log"
)

func main() {
	c := cron.New(cron.WithSeconds())
	spec := "* * * * * *"
	res := []int{1,2}
	for _,i := range res {
		c.AddFunc(spec, func() {
			log.Println("cron running:",i)
		})
	}
	c.Start()
        defer c.Stop()

	select{}
}
#expected output
2019/11/17 12:01:31 cron running: 1
2019/11/17 12:01:31 cron running: 2
#real output
2019/11/17 12:01:31 cron running: 2
2019/11/17 12:01:31 cron running: 2

So could someone tell me

**Comment by robfig** [comment]
Here is an explanation:
https://github.com/golang/go/wiki/CommonMistakes

**Comment by lixiangzzz2017** [comment]
Thanks a lot.I use goroutines to do this,and it worked.
