### ISSUE TITLE
go get 410 Gone

### ISSUE THREAD

**Issue by lb151** [robfig/cron#254]
E:\go\test>go get github.com/robfig/cron/v3@v3.0.0
go: finding github.com v3.0.0
go: finding github.com/robfig v3.0.0
go: finding github.com/robfig/cron v3.0.0
go: downloading github.com/robfig/cron/v3 v3.0.0
verifying github.com/robfig/cron/v3@v3.0.0: github.com/robfig/cron/v3@v3.0.0: reading https://goproxy.io/sumdb/sum.golang.org/lookup/github.com/robfig/cron/v3@v3.0.0: 410 Gone

**Comment by RonaldZhao** [comment]
+1
