### ISSUE TITLE
Question on Job specification

### ISSUE THREAD

**Issue by deranjer** [robfig/cron#257]
Hopefully quick question on what I am missing here.

I am attempting to create a job, I need a job since I need to skip if the job is still running since it could be running for a long time.  However, I can't figure out the correct way to actually define the job logic so I ended up converting a function to a job, but not sure if that is the right approach.  Here is my current testing code (which does work fine, but assume I'm not doing it the correct way).

```
var Logger *lecho.Logger
func ingressJobFunc() {
	fmt.Println("Testing job func")
}

//InitialzeSchedules starts all the cron jobs (currently just one)
func InitializeSchedules(db *storm.DB) {
	serverConfig := database.FetchConfigFromDB(db)
	c := cron.New(cron.WithLogger(cron.VerbosePrintfLogger(Logger)))
	var ingressJob cron.Job
	ingressJob = cron.FuncJob(ingressJobFunc)
	ingressJob = cron.NewChain(cron.SkipIfStillRunning(cron.DefaultLogger)).Then(ingressJob)
	serverConfig.IngressInterval = 1
	c.AddJob(fmt.Sprintf("@every %dm", serverConfig.IngressInterval), ingressJob)
	c.Start()

}
```

**Comment by robfig** [comment]
Yep, that will work fine. Alternatively, you could define a type for your ingress job and implement the cron.Job interface.  There is no difference from cron's point of view though.
