### ISSUE TITLE
[Feature Request] Add Delay in the first execution for the @every scheduled actions

### ISSUE THREAD

**Issue by toni-moreno** [robfig/cron#258]
Hi everybody. 
In my use case we need schedule a lot of jobs @every "X time" . When restart my service all jobs will begin at the same time if X time is similar .

Suppose you need jobs each 10m , if you have 10k jobs all jobs will start at the same time. I suggest add a "delay Xm" or "delay @random[0,10]m" to enable restart all jobs at the same time, and avoid overload on the hardware only 1/2 minutes instead of share cpu/mem time on all jobs.

Delay time should be added only on the first execution.

The configuration could be something similar to:

@every 10m, @delay 1m
@everys 10m,@delay @random[0,9]m

What do you think about?

Thank you very much!

**Comment by robfig** [comment]
That is an interesting point. Adding some jitter on startup makes a lot of sense. I think that you could implement that by making a custom JitteredSchedule that wraps the builtin SpecSchedule. It would be nice if the offset could be determined automatically, but I suppose it would be too hard to account for the various cases (e.g. for short running jobs, maybe offset by 50ms is enough, but for 10m jobs, you might want more). 

I believe that you can implement in your own codebase and see how it goes.

**Comment by robfig** [comment]
Alternatively, I would be happy to support the "H" modifier described at the bottom of https://en.wikipedia.org/wiki/Cron. Would that solve your use case?
