### ISSUE TITLE
Putting the clock forwards causes cron to catch-up and run multiple times

### ISSUE THREAD

**Issue by ahall** [robfig/cron#26]
If you set a job to run @every 5s and start it works perfectly within my test program. However if you put the clock fowards an hour it will run approximately 720 times as the effective time will be playing catch-up with the current time (now). This can happen when laptops goes to sleep and then wake up. This is the issue I'm facing and my maintenance tasks to run multiple times on laptop resume.

By quickly taking a look I think the fix is to change line 161 from:

```
e.Next = e.Schedule.Next(effective)
```

To

```
e.Next = e.Schedule.Next(now)
```

I don't want to patch my code with this before you agree that this fix is correct. Please let me know.

**Comment by robfig** [comment]
I think that the reason I used 'effective' instead of 'now' is to avoid missing jobs in case of random pauses.  I agree that your use case seems pretty motivating to adjust things.  All of the tests pass when I make the change you describe, so at least I doesn't break anything in the typical case.

Want to give it a shot and report back how it goes?

**Comment by ahall** [comment]
Yeah will do. I have tested messing around with the clock and everything works fine with the change. Normal behaviour seems ok so I think it will be fine. I will report back in few weeks and let you know how it goes.

**Comment by ahall** [comment]
Hi @robfig, thought I'd report back.

I've been using my patch now in production for few days and this has solved my problems and doesn't seem to have had any regression effects. Should we push this fix to master?

**Comment by robfig** [comment]
Good to hear!  My only concern is the behavior during daylight savings transitions.  I'm not sure how to test that though..

**Comment by dvdplm** [comment]
Is this fix currently under consideration for v2?

**Comment by robfig** [comment]
Sure, I'm happy to merge it

**Comment by dvdplm** [comment]
Lovely! :)

**Comment by robfig** [comment]
I believe this was merged and all good. Closing
