### ISSUE TITLE
Does cron support "exception date-time" ?

### ISSUE THREAD

**Issue by csqshz** [robfig/cron#262]
**For example:**
I have a task with two types of date-time:

**type 1 is normal date-time:**
[start: 2019-1.1](url)
[end : 2019-1.10](url)
time: 10:00 am
action: do A

**type 2 is exception date-time:**
[date: 2019-1.5](url)
time: 9:00 am
action: do B

The actual project maybe more complicated than above.
So simply dividing the above time to 
>2019-1.1>2019.1.4
>2019-1.5
>2019-1.6>2019.1.10

is improper.

**Comment by robfig** [comment]
That is not supported by this library. You would have to arrange for that in your own code, sorry!
