### ISSUE TITLE
import "github.com/robfig/cron/v3" failed

### ISSUE THREAD

**Issue by MirkoWu** [robfig/cron#267]
go: downloading github.com/robfig/cron/v3 v3.0.0
go: downloading github.com/robfig/cron v1.2.0
verifying github.com/robfig/cron/v3@v3.0.0: github.com/robfig/cron/v3@v3.0.0: Get https://sum.golang.org/lookup/github.com/robfig/cron/v3@v3.0.0: dial tcp 172.217.24.17:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

**Comment by robfig** [comment]
What version of Go are you using? Are you still having a problem?

**Comment by luthfikw** [comment]
same issues, but different message

go version go1.12.9 darwin/amd64

```
$ go get github.com/robfig/cron/v3@v3.0.0
go: github.com/robfig/cron@v0.0.0-20200104010508-ccba498c397b: go.mod has post-v0 module path "github.com/robfig/cron/v3" at revision ccba498c397b
go: error loading module requirements
```

**Comment by dragstor** [comment]
Use `"gopkg.in/robfig/cron.v3"` for imports.
Also,

`go get gopkg.in/robfig/cron.v3` in term.

**Comment by luthfikw** [comment]
@dragstor when i used gopkg.in
at go mod tidy, just download and forget that

go version go1.12.9 darwin/amd64

![Screen Shot 2020-01-07 at 10 41 23](https://user-images.githubusercontent.com/49427666/71866866-60caf780-313a-11ea-856d-6579c1a6c3fe.png)

**Comment by dragstor** [comment]
> @dragstor when i used gopkg.in
> at go mod tidy, just download and forget that
> 
> go version go1.12.9 darwin/amd64
> 
> ![Screen Shot 2020-01-07 at 10 41 23](https://user-images.githubusercontent.com/49427666/71866866-60caf780-313a-11ea-856d-6579c1a6c3fe.png)

I don't get it - you managed to import it or not?

**Comment by robfig** [comment]
I do not believe that Go Modules works with gopkg.in, because Go Modules requires that you import the module using the canonical import path.

I believe you have to import it like this:
```
import "github.com/robfig/cron/v3"
```

It works for me:
```
$ go mod init test.com/m
go: creating new go.mod: module test.com/m

$  go get github.com/robfig/cron/v3@v3.0.1
go: finding github.com v3.0.1
go: finding github.com/robfig v3.0.1
go: finding github.com/robfig/cron/v3 v3.0.1
go: finding github.com/robfig/cron v3.0.1
go: downloading github.com/robfig/cron/v3 v3.0.1
go: extracting github.com/robfig/cron/v3 v3.0.1
```

**Comment by luthfikw** [comment]
> I do not believe that Go Modules works with gopkg.in, because Go Modules requires that you import the module using the canonical import path.
> 
> I believe you have to import it like this:
> 
> ```
> import "github.com/robfig/cron/v3"
> ```
> 
> It works for me:
> 
> ```
> $ go mod init test.com/m
> go: creating new go.mod: module test.com/m
> 
> $  go get github.com/robfig/cron/v3@v3.0.1
> go: finding github.com v3.0.1
> go: finding github.com/robfig v3.0.1
> go: finding github.com/robfig/cron/v3 v3.0.1
> go: finding github.com/robfig/cron v3.0.1
> go: downloading github.com/robfig/cron/v3 v3.0.1
> go: extracting github.com/robfig/cron/v3 v3.0.1
> ```

working well with this,
i think gopkg.in working well on go13.xx

**Comment by denghuancong** [comment]
try many methods , it not works, how difficult to use.
```
go: git.xx.com/xx/schedule imports
        gopkg.in/robfig/cron.v3: gopkg.in/robfig/cron.v3@v3.0.1: parsing go.mod:
        module declares its path as: github.com/robfig/cron/v3
                but was required as: gopkg.in/robfig/cron.v3
```

**Comment by robfig** [comment]
The error message says what's wrong:
```
go: git.xx.com/xx/schedule imports
        gopkg.in/robfig/cron.v3:
```

Your package imports "gopkg.in/robfig/cron.v3". 

Instead, it should import "github.com/robfig/cron/v3"

**Comment by TaukeKhan99** [comment]
> I do not believe that Go Modules works with gopkg.in, because Go Modules requires that you import the module using the canonical import path.
> 
> I believe you have to import it like this:
> 
> ```
> import "github.com/robfig/cron/v3"
> ```
> 
> It works for me:
> 
> ```
> $ go mod init test.com/m
> go: creating new go.mod: module test.com/m
> 
> $  go get github.com/robfig/cron/v3@v3.0.1
> go: finding github.com v3.0.1
> go: finding github.com/robfig v3.0.1
> go: finding github.com/robfig/cron/v3 v3.0.1
> go: finding github.com/robfig/cron v3.0.1
> go: downloading github.com/robfig/cron/v3 v3.0.1
> go: extracting github.com/robfig/cron/v3 v3.0.1
> ```

Are you using GoLand? I imported in this way, but GoLand doesn't index it and import marked as red. The program works correctly. Problem is library exists in go.mod and works but doesn't exist in my local storage(folder)
