### ISSUE TITLE
pipe2: too many open files

### ISSUE THREAD

**Issue by Lonenso** [robfig/cron#269]
I was trying to see how much concurrency "cronV3" could carry at same time. So I wrote a demo below. And error occurs. Maybe I forgot to close some resource, but it doesn't obvious to me . Need some help, thanks

* pipe2 too many open files 

GoVersion 1.13.1 
GOOS/GOARCH =  linux/amd64
OS/Kernel = Centos 6.9/4.15.7

ulimit -n 
> 1024

```
package main

import (
	"log"
	"os/exec"
	"time"

	"github.com/robfig/cron/v3"
)

func main(){
	c := cron.New(cron.WithSeconds())
	quit := make(chan struct{})
	for i:=0; i< 1024; i++{
		eid, err := c.AddFunc("*/5 * * * * *", func(){
			output, err := exec.Command("bash", "-c", "--", "echo hello world").CombinedOutput()
			log.Printf("%v, %v", string(output), err)
			if err != nil{
				log.Printf("error occurs\n")
				c.Stop()
				quit <- struct{}{}
			}
		})
		if err != nil{
			panic(err)
		}
		log.Printf("%v\n", eid)
	}
	time.Sleep(15 * time.Second)
	c.Start()
	<- quit
}


```

**Comment by robfig** [comment]
I think you're running out of file descriptors because of running many concurrent instances of exec.Command. It has nothing to do with cron. You can verify that by removing cron and just running "go func() { ... " instead.
