### ISSUE TITLE
cron doesn't work anyway, is there something i did wrong?

### ISSUE THREAD

**Issue by HaoBofei** [robfig/cron#278]
here's the code:
c := cron.New()
	c.AddFunc("*/2 * * * * *", func() {
		fmt.Println("!!!!!")
	})
	c.Start()

but there's no print
maybe this is a simple issue, but i can't fix it
my os is windows10
import "gopkg.in/robfig/cron.v3"
or import "github.com/robfig/cron"
none of them is ok

**Comment by kritzware** [comment]
Same issue for me, running the exact same code above on Mac OS.

```go
c := cron.New()
c.AddFunc("*/2 * * * * *", func() {
fmt.Println("!!!!!")
})
c.Start()
```

**Comment by robfig** [comment]
What behavior are you seeing? Can you post a complete program?

My guess is that your `main()` returns, exiting the program before the job runs. `cron.Start()` starts it in a new goroutine and returns. Use `cron.Run()` to block.

**Comment by kritzware** [comment]
My mistake, you're exactly right about using `cron.Run()` instead of `cron.Start()`. Thanks!
