### ISSUE TITLE
How can i identify specific cron job ?

### ISSUE THREAD

**Issue by atul161** [robfig/cron#284]
I have a scenerio where i have to start a  cron job for each user .
So how can i specify a cron job so that i can stop particular cron job.
or update a cron job in the mid of its execution?

**Comment by robfig** [comment]
Methods to add a job return an EntryID that you can use to subsequently remove it.
https://godoc.org/github.com/robfig/cron#Cron.AddJob
https://godoc.org/github.com/robfig/cron#Cron.Remove
