### ISSUE TITLE
Flesh out README

### ISSUE THREAD

**Issue by blalor** [robfig/cron#29]
It'd be helpful if the README at least had a subset of the examples in the godocs, as well as a pointer that the user should be using the gopkg.in paths.

**Comment by elgs** [comment]
https://github.com/elgs/cron

Here is a deviation with some better-than-nothing examples, and with additional remove/pause/resume/status functions.

**Comment by qiukeren** [comment]
I think you'd better issue a push request @elgs

**Comment by robfig** [comment]
The godoc link is prominently featured, which is where the docs reside.  I think that is common practice for go packages...
