### ISSUE TITLE
provide a way to set timezone of schedule?

### ISSUE THREAD

**Issue by JellyZhang** [robfig/cron#293]
Here is a thing , i only need to parse a cron string and get a schedule to call Next() function。
As mentioned in doc, using 'TZ=' prefix can specfic a timezone with city name.
(since the parsh() called` time.LoadLocation()`)。

here i have one custom timezone generated by `time.FixedZone("XXX",1234)` and I can not pass it to parse since it is not a city name can stand for it.

**Comment by robfig** [comment]
For this case, you should add your job using [`cron.Schedule`](https://godoc.org/github.com/robfig/cron#Cron.Schedule), which allows you to provide your own schedule, containing a Location. 

To get a schedule, call [`cron.ParseStandard`](https://godoc.org/github.com/robfig/cron#Cron.ParseStandard), assert the returned schedule's type to be `cron.SpecSchedule` and then set the Location property on it directly. Sorry it's a bit roundabout!

**Comment by JellyZhang** [comment]
> For this case, you should add your job using [`cron.Schedule`](https://godoc.org/github.com/robfig/cron#Cron.Schedule), which allows you to provide your own schedule, containing a Location.
> 
> To get a schedule, call [`cron.ParseStandard`](https://godoc.org/github.com/robfig/cron#Cron.ParseStandard), assert the returned schedule's type to be `cron.SpecSchedule` and then set the Location property on it directly. Sorry it's a bit roundabout!

Thanks, It's done. I'll close it.
