### ISSUE TITLE
Fixed Rate、Fixed Delay

### ISSUE THREAD

**Issue by wangbaolong** [robfig/cron#294]
Can you support something similar to Java fixed rate and fixed delay

**Comment by robfig** [comment]
The current schedule supports fixed rate. If you need fixed delay, you could implement that with a custom schedule relatively easily. Schedule is an interface so anyone can plug in their desired scheduling policy. For built-in schedules, I think it's important to stick to the "official spec".

**Comment by robfig** [comment]
Sorry, I responded too quickly. There's no way to implement a fixed delay because we do not track the time at which a job completes.
