### ISSUE TITLE
cron does not work

### ISSUE THREAD

**Issue by AdorableParker** [robfig/cron#295]
I encountered a problem similar to this.
This is my code:
```go
package main

import (
	"fmt"
	"github.com/robfig/cron/v3"
)

func main() {
	c := cron.New()
	spec := "*/2 * * * * *"
	c.AddFunc(spec, func() { 
		fmt.Println("cron running")
	})
	// c.Start()
	c.Run()
	select {}
}
```
He has no output.
I read similar issues in the issues,   #278 
but they have not been resolved, I don't know where I am doing wrong.

**Comment by robfig** [comment]
The schedule you printed will cause it to run only after 2 minutes. If you meant to run every 2 seconds, use `cron.WithSeconds()` in the constructor. That works for me:
https://play.golang.org/p/U5BX4KTgURg

**Comment by XswSavage** [comment]
`
package main

import (
	"fmt"
	"github.com/robfig/cron"
)

func main() {
	c := cron.New(cron.WithSeconds())
	c.AddFunc("0/1 * * * *", func() { fmt.Println("running") })
	c.Run()
	select {}
}
`
// but... no print
