### ISSUE TITLE
Stop a not running cron block program

### ISSUE THREAD

**Issue by cgarnier** [robfig/cron#30]
Hello,
I think that when Stop() is called on a not running cron, it block the program.
Is there a when to know if cron is started ? running is private.

**Comment by elgs** [comment]
I have added RemoveFunc, PauseFunc, ResumeFunc and Status here: https://github.com/elgs/cron.

**Comment by alaska** [comment]
If it's fully tested, I think this should be merged.  These are good to have.

**Comment by elgs** [comment]
I wish it would be merged since about 1 year ago, but it seems @robfig is not interested in these new features. So I have to switch my modified version. I have been using my version for about 1 year in my projects. All seem to be good.

**Comment by dvdplm** [comment]
This seems worrying. Any chance we can get this fixed on the main repo @robfig ?

**Comment by robfig** [comment]
I would be happy to accept a pull request that returned immediately from Stop() if the cron was not running.  Regarding elgs' additional features, I did not consider them to be addressing the majority use case and didn't want to be responsible for maintaining the code.  This package is meant to be stable / done, and I don't see the harm in him using his own fork that meets his need.

**Comment by dvdplm** [comment]
@robfig thanks for the update, I'll see what I can come up with. :)

**Comment by dvdplm** [comment]
afaict this issue is not an issue. `Stop()` does not block my program and the existing test for it seems fine also. I think it's safe to close.

**Comment by robfig** [comment]
Great news, thanks for testing it out!
