### ISSUE TITLE
Nill pointer exceptions

### ISSUE THREAD

**Issue by Kartikkh** [robfig/cron#301]
hi Robfig, 
I am thankful to you for providing such amazing corn support in Golang. I have been using this for a while now, it is very cleanly, nicely and abstractly written, making our tasks quite easier to deliver. 
But of late I started to face this panic 

socketmaster[21064] 2020/04/13 12:00:00 [1978] 2020/04/13 12:00:00 cron.go:229: cron: panic running job: runtime error: invalid memory addres
s or nil pointer dereference
socketmaster[21064] 2020/04/13 12:00:00 [1978] goroutine 436 [running]:
socketmaster[21064] 2020/04/13 12:00:00 [1978] github.com/XXX/XXX/vendor/github.com/robfig/cron.(*Cron).runWithRecovery.func1(0xc42
028ee60)
socketmaster[21064] 2020/04/13 12:00:00 [1978]  /share/dpkg-build/XXX-build/src/github.com/XXX/XXX/vendor/github.com/robfig/cro
n/cron.go:161 +0xbc
socketmaster[21064] 2020/04/13 12:00:00 [1978] panic(0x8b10c0, 0xc3ec90)
socketmaster[21064] 2020/04/13 12:00:00 [1978]  /home/buildbot/.gvm/gos/go1.10/src/runtime/panic.go:505 +0x229
socketmaster[21064] 2020/04/13 12:00:00 [1978] github.com/XXX/XXX/vendor/github.com/robfig/cron.FuncJob.Run(0x0)
socketmaster[21064] 2020/04/13 12:00:00 [1978]  /share/dpkg-build/XXX-build/src/github.com/XXX/XXX/vendor/github.com/robfig/cro
n/cron.go:92 +0x20
socketmaster[21064] 2020/04/13 12:00:00 [1978] github.com/XXX/XX/vendor/github.com/robfig/cron.(*Cron).runWithRecovery(0xc42028ee6
0, 0xa14320, 0x0)
socketmaster[21064] 2020/04/13 12:00:00 [1978]  /share/dpkg-build/XX-build/src/github.com/XXX/XXX/vendor/github.com/robfig/cro
n/cron.go:165 +0x57
socketmaster[21064] 2020/04/13 12:00:00 [1978] created by github.com/XXX/XXXX/vendor/github.com/robfig/cron.(*Cron).run
socketmaster[21064] 2020/04/13 12:00:00 [1978]  /share/dpkg-build/xxx-build/src/github.com/XXX/XXX/vendor/github.com/robfig/cro
n/cron.go:199 +0x744

I tried to deep dive into this. But didn't got any proper solution to this problem. So I request to help me.

**Comment by robfig** [comment]
Thank you for the kind words.

The stack trace reports that it was trying to run a nil job. Is it possible that one of the jobs added was not initialized?

**Comment by Kartikkh** [comment]
@robfig No, it is not possible 
The job we add is always initialized

**Comment by robfig** [comment]
I'm sorry, I don't know what else it could be. I would need a reproducer to investigate. Please do reopen if that's possible, but since it's been a long time, I assume this is no longer a problem.
