### ISSUE TITLE
program ends even after using recoverer

### ISSUE THREAD

**Issue by da-revo** [robfig/cron#304]
**program ends even after using recoverer**

### here is how I set it up:
`
var defaultLogger cron.Logger; 
c := cron.New(cron.WithChain(
	cron.Recover(defaultLogger),
));
c.AddFunc("@every 0h0m3s", HourlyCronJobs);
c.AddFunc("@every 0h5m0s", func() { println("It's 5 minutes") });
c.Start();
`
### output:
`running hourly cron
null
panic: runtime error: index out of range [0] with length 0 [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x7d14cf]

goroutine 51 [running]:
github.com/robfig/cron.Recover.func1.1.1(0x0, 0x0)
	/home/bo/development/go-workspace/src/github.com/robfig/cron/chain.go:50 +0x1af
panic(0x92c6a0, 0xc000110120)
	/home/bo/go/src/runtime/panic.go:679 +0x1b2
main.HourlyCronJobs()
	/home/bo/coding_projects/pl-server/cron.go:34 +0x5ec
github.com/robfig/cron.FuncJob.Run(0x98b5c8)
	/home/bo/development/go-workspace/src/github.com/robfig/cron/cron.go:136 +0x25
github.com/robfig/cron.Recover.func1.1()
	/home/bo/development/go-workspace/src/github.com/robfig/cron/chain.go:53 +0x7f
github.com/robfig/cron.FuncJob.Run(0xc0000fc270)
	/home/bo/development/go-workspace/src/github.com/robfig/cron/cron.go:136 +0x25
github.com/robfig/cron.(*Cron).startJob.func1(0xc0001280a0, 0xa18800, 0xc0000fc270)
	/home/bo/development/go-workspace/src/github.com/robfig/cron/cron.go:312 +0x69
created by github.com/robfig/cron.(*Cron).startJob
	/home/bo/development/go-workspace/src/github.com/robfig/cron/cron.go:310 +0x73
exit status 2
`

**Comment by robfig** [comment]
`c.Start()` starts another goroutine, and then your program exits normally. Use `c.Run()` instead.

**Comment by da-revo** [comment]
**with c.Run()** :
`
var defaultLogger cron.Logger;
c := cron.New(cron.WithChain( cron.Recover(defaultLogger), ));
c.AddFunc("@every 0h0m3s", HourlyCronJobs);
c.Run();
log.Fatal(server.ListenAndServe());
c.Stop();
`
**output:**
`
running hourly cron
null
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x7fda1f]

goroutine 35 [running]:
github.com/robfig/cron.Recover.func1.1.1(0x0, 0x0)
	/home/bo/development/go-workspace/src/github.com/robfig/cron/chain.go:50 +0x1af
panic(0x90b0a0, 0xd81500)
	/home/bo/go/src/runtime/panic.go:679 +0x1b2
main.HourlyCronJobs()
	/home/bo/coding_projects/pl-server/cron.go:29 +0x2c8
github.com/robfig/cron.FuncJob.Run(0x9bcfa8)
	/home/bo/development/go-workspace/src/github.com/robfig/cron/cron.go:136 +0x25
github.com/robfig/cron.Recover.func1.1()
	/home/bo/development/go-workspace/src/github.com/robfig/cron/chain.go:53 +0x7f
github.com/robfig/cron.FuncJob.Run(0xc000126120)
	/home/bo/development/go-workspace/src/github.com/robfig/cron/cron.go:136 +0x25
github.com/robfig/cron.(*Cron).startJob.func1(0xc00012e0a0, 0xa4e9a0, 0xc000126120)
	/home/bo/development/go-workspace/src/github.com/robfig/cron/cron.go:312 +0x69
created by github.com/robfig/cron.(*Cron).startJob
	/home/bo/development/go-workspace/src/github.com/robfig/cron/cron.go:310 +0x73
exit status 2

`
thanks anyway

**Comment by robfig** [comment]
In that example, you're passing a nil cron.Logger. Instead of that, do 
```
cron.Recover(cron.DefaultLogger)```
