### ISSUE TITLE
cron job not work

### ISSUE THREAD

**Issue by fuguohong1024** [robfig/cron#305]
testcode
`package main

import (
	"fmt"
	"log"

	"github.com/robfig/cron/v3"
)

func main() {
	log.Println("Starting...")

	c := cron.New()  // 新建一个定时任务对象
	EntryID,_ := c.AddFunc("* * * * * *", func() {
		log.Println("hello world")
	})  // 给对象增加定时任务
	fmt.Println(EntryID)
	c.Start()
	select {
	}
}`

log.Println like this:
`2020/05/04 15:42:47 Starting...
0
`

i`m sure the  program not exited,and i try use c.Run() also. but nothing ,no hello world,

**Comment by fuguohong1024** [comment]
emmmm, i import `"github.com/robfig/cron"` and `c := cron.New()
	c.AddFunc(spec,sendMail)
	c.Run()
	select {

	}`  is work

**Comment by lvxiaorun** [comment]
I have the same problem, why V3 doesn't work
