### ISSUE TITLE
vendor/github.com/robfig/cron/logger.go:62:9: undefined: strings.Builder 

### ISSUE THREAD

**Issue by akaDPR** [robfig/cron#306]
`vendor/github.com/robfig/cron/logger.go:62:9: undefined: strings.Builder` 

Why I'm getting this error when installing my go-app using dockerfile

**Comment by rouzier** [comment]
It seems you are not using the right version of go.
strings.Builder was introduced in 1.10 https://golang.org/pkg/strings/#Builder

**Comment by robfig** [comment]
This library requires Go 1.11 at least for Modules support. You could probably use an older version (v1), but I'm not under the impression that there's a major reason to run such old versions of Go.
