### ISSUE TITLE
Can not construct cron obj with a custom parser

### ISSUE THREAD

**Issue by vankofalcon** [robfig/cron#313]
I'm using go 1.14 with go mod github.com/robfig/cron/v3 v3.0.1

```
import "github.com/robfig/cron/v3"

cron.New(
		cron.WithParser(
			cron.SecondOptional | cron.Minute | cron.Hour | cron.Dom | cron.Month | cron.Dow | cron.Descriptor))
```

`Cannot use 'cron.SecondOptional | cron.Minute | cron.Hour | cron.Dom | cron.Month | cron.Dow | cron.Descriptor' (type ParseOption) as type ScheduleParser Type does not implement 'ScheduleParser' as some methods are missing: Parse(spec string) (Schedule, error)`

seems that the example in the readme is wrong. How can I do that?

**Comment by overthetop** [comment]
I've found out what's wrong 
https://github.com/robfig/cron/pull/314
