### ISSUE TITLE
Problem with removing Crons

### ISSUE THREAD

**Issue by JaanusM** [robfig/cron#315]
So i have lilte app what crawls querys from Rest API, 

Would like to add Cron Jobs to that, but having issues where "Remove(cronEntryID)" is not doing anything. 

using: "github.com/robfig/cron/v3"

Here is how i get EntryID for CronJob
```

SqlCronId, _ = sqlCron.AddFunc(CronTime, func() {
sqlJob(myParams, go, here)
})

```

Also, while there may be many Crons then i add thouse ID-s to array
`sqlCronIDarray = append(sqlCronIDarray, SqlCronId)`

And once app gets notification that something is updated, then it will drop everything what it has

So there i will take my cronJob and try to remove all rows: 

```
i:= 0
for range sqlCronIDarray {
	cronEntryID = sqlCronIDarray[i]
	sqlCron.Remove(cronEntryID) //TODO: somehow are they not removed?
	i++
}
sqlCronIDarray = nil //Empty array also`

```
---
Tried to add sqlCron.Stop()  before  removing but  did not help. 

Strange is that when i use just: sqlCron.Remove(1) -- Then it works like a charm.

In my case it would be very nice to have something like   cron.Reset() function what gets rid off all Cron Jobs :)

**Comment by JaanusM** [comment]
Well and a strange one on deleting.. 

**log.Println(sqlCron.Entries())** Gives me right result: 
```
[{1 0xc000550b80 2020-05-18 16:44:00 +0300 EEST 0001-01-01 00:00:00 +0000 UTC 0x857330 0x857330} 
{2 0xc0005b3340 2020-05-18 16:44:00 +0300 EEST 0001-01-01 00:00:00 +0000 UTC 0x857330 0x857330} 
{3 0xc0005faa00 2020-05-18 16:44:00 +0300 EEST 0001-01-01 00:00:00 +0000 UTC 0x857330 0x857330}]
```

But in reality "Old processes" are still running somewhere in the background: 
The thing here is that one row was added ("Every Minute 3") before that there was sqlCron.Remove()

And the result is that old two remained in cron, and all 3 where there for extra, so 5 Cron jobs instead of 3 what would be right: 
```
2020/05/18 16:44:00 Starting SQL query for: Every Minute 1 
2020/05/18 16:44:00 Starting SQL query for: Every minute 2 
2020/05/18 16:44:00 Starting SQL query for: Every Minute 1 
2020/05/18 16:44:00 Starting SQL query for: Every minute 2 
2020/05/18 16:44:00 Starting SQL query for: Every Minute 3 
```

**Comment by robfig** [comment]
If Entries() gives you the right result, my only guess is that the jobs are not exiting. Is it possible that they do not return in a timely fashion?

**Comment by JaanusM** [comment]
> If Entries() gives you the right result, my only guess is that the jobs are not exiting. Is it possible that they do not return in a timely fashion?

Well my function has an an end, and i try to remove crons on next function start. (function is called with every query..) 

Probably i need to make thouse crons in "Entry" global somehow?

**Comment by JaanusM** [comment]
So Litle more information: 

i have separate Go Routine what is responsiple for row updates.

It is in for loop, so will never end. 
thisone calls out updating rows and there is the place where i would like to reset all Crons and add new ones. 

```
	var sqlUpdate sync.WaitGroup
	go func() { //Check if we have newer Elastic rows in Insight
		for {
			sqlLastUpdate = checkInsightUpdate("SQL")
			if sqlDatasetTimestamp != sqlLastUpdate {

				sqlUpdate.Add(1) // Updating job rows

				INS_SQL.Reset() //Reset SQL prometheus metrics, so that Old metrics will be dropped
				SQLQueryJsonArray = nil
				log.Println("Updating SQL rows from insight!")

				insightPull("SQL") //Gets new SQL rows from insightPull.go

				sqlDatasetTimestamp = sqlLastUpdate

				sqlUpdate.Done() // Done update
			}
			time.Sleep(time.Duration(inRowUpdateCheck) * time.Minute)
		}
	}()
```

in insightPull("SQL") i do request against rest api and get my SQL querys from Json.

it starts like so: 
```
func insightPull(queryType string) {
	sqlCron := cron.New()
	sqlCron.Start() //Start cron
	log.Println("Updating dataset from insight for ", queryType)
.....
```


here is how i set My Cron: 
				```
	CronTime := objectAtributes.ObjectEntries[i].Attributes[CronFieldIndex].ObjectAttributeValues[0].DisplayValue
					log.Println(Name, Key, "is cronJob, will add new Cron with Expression:", CronTime)

					SqlCronId, _ = sqlCron.AddFunc(CronTime, func() {
						sqlJob(Host, dbSecretUserFieldValue, dbSecretPasswordFieldValue, Port, Database, Name, Key, Query, App)
					})
```

And some additional logs: 
on first run, it Fills **sqlCron.Entries()** and they are shown after they are added.


`2020/05/19 13:51:45  CronJobs are: [{1 0xc000488980 2020-05-19 13:52:00 +0300 EEST 0001-01-01 00:00:00 +0000 UTC 0x857240 0x857240} {2 0xc000522340 2020-05-19 13:52:00 +0300 EEST 0001-01-01 00:00:00 +0000 UTC 0x857240 0x857240} {3 0xc00066d0c0 2020-05-19 13:52:00 +0300 EEST 0001-01-01 00:00:00 +0000 UTC 0x857240 0x857240}]`

Also they run fine, and there are no issues with them. Until i need to update/ remove them.
(All SQL Querys are select count(1)
2020/05/19 14:00:00 OS-27967 Every minute 2 == 1
2020/05/19 14:00:00 OS-27968 Every Minute 3 == 1
2020/05/19 14:00:00 OS-27966 Every Minute 1 == 1

On the next run when  insightPull("SQL") is called says the same line:  **sqlCron.Entries()**
2020/05/19 13:52:48 CronJobs are: []  <- Jup its empty without any removing done.

after second run of insightPull("SQL"): 
2020/05/19 14:01:14 CronJobs are: [{1 0xc0001096c0 2020-05-19 14:02:00 +0300 EEST 0001-01-01 00:00:00 +0000 UTC 0x857240 0x857240} {2 0xc000463940 2020-05-19 14:02:00 +0300 EEST 0001-01-01 00:00:00 +0000 UTC 0x857240 0x857240} {3 0xc0006026c0 2020-05-19 14:02:00 +0300 EEST 0001-01-01 00:00:00 +0000 UTC 0x857240 0x857240}]

And the fun part starts here: in the end logs say that there are 3 Crons in Entries, but once it gets to the crons, there are dublicate crons (Oldones and new) and all of them are called and runned.

```
2020/05/19 14:02:00 Starting SQL query for: Every Minute 1 OS-27966
2020/05/19 14:02:00 Starting SQL query for: Every minute 2 OS-27967
2020/05/19 14:02:00 Starting SQL query for: Every minute 2 OS-27967
2020/05/19 14:02:00 Starting SQL query for: Every Minute 1 OS-27966
2020/05/19 14:02:00 Starting SQL query for: Every Minute 3 OS-27968
2020/05/19 14:02:00 Starting SQL query for: Every Minute 3 OS-27968
2020/05/19 14:02:00 OS-27968 Every Minute 3 == 1
2020/05/19 14:02:00 OS-27966 Every Minute 1 == 1
2020/05/19 14:02:00 OS-27966 Every Minute 1 == 1
2020/05/19 14:02:00 OS-27968 Every Minute 3 == 1
2020/05/19 14:02:00 OS-27967 Every minute 2 == 1
2020/05/19 14:02:00 OS-27967 Every minute 2 == 1
```

So somehow **sqlCron.Entries()** does not show them, but they still exist somewhere in the darkness.. 

But when i try to remove them, then they dont exist..

**Comment by JaanusM** [comment]
Well found solution, that´s not pretty but works.. 

Moved them directly inside my  separate go routine what never stops: 

```
var sqlUpdate sync.WaitGroup
	go func() { //Check if we have newer SQL rows in Insight
		sqlCron := cron.New()
		for {
			sqlLastUpdate = checkInsightUpdate("SQL")
			if sqlDatasetTimestamp != sqlLastUpdate {
				log.Println("Crons before stop", sqlCron.Entries()) //Print out all jobs here
				sqlCron.Stop()                                      //Stop SQL Cron Jobs here
				//remove crons here if there are 6 items in Entry After run 2

				sqlUpdate.Add(1) // Updating job rows

				INS_SQL.Reset()             //Reset SQL prometheus metrics, so that Old metrics will be dropped
				SQLQueryJsonArray = nil     // Empty SQL job list
				SQLCronQueryJsonArray = nil // Empty CronJob list
				log.Println("Updating SQL rows from insight!")

				insightPull("SQL") //Gets new SQL rows from insightPull.go

				sqlDatasetTimestamp = sqlLastUpdate

				//Add new Crons here

				//SQLCronQueryJsonArray -- Loop this one for sqlCronJobs
				var InsightSqlCRONObject InsightSqlCRONObject
				for range SQLCronQueryJsonArray {
					i := 0
					json.Unmarshal([]byte(SQLCronQueryJsonArray[i]), &InsightSqlCRONObject)

					SqlCronId, _ = sqlCron.AddFunc(InsightSqlCRONObject.CronTime, func() {
						sqlJob(InsightSqlCRONObject.Host,
							InsightSqlCRONObject.DbSecretUserField,
							InsightSqlCRONObject.DbSecretPasswordField,
							InsightSqlCRONObject.Port,
							InsightSqlCRONObject.Database,
							InsightSqlCRONObject.Name,
							InsightSqlCRONObject.Key,
							InsightSqlCRONObject.Query,
							InsightSqlCRONObject.App)
					})
					i++
				}

				sqlCron.Start()                                     //Start SQL Cron jobs
				log.Println("Crons after start", sqlCron.Entries()) //Print out all jobs here
				sqlUpdate.Done()                                    // Done update
			}
			time.Sleep(time.Duration(inRowUpdateCheck) * time.Minute)
		}
	}()
```
And result before removing: (Second run): 
**Crons added on first run are present now:** 

`2020/05/19 14:57:28 Crons before stop [{1 0xc0000c8240 2020-05-19 14:58:00 +0300 EEST 2020-05-19 14:57:00 +0300 EEST 0x8573e0 0x8573e0} {2 0xc0000c8280 2020-05-19 14:58:00 +0300 EEST 2020-05-19 14:57:00 +0300 EEST 0x8573e0 0x8573e0} {3 0xc0000c82c0 2020-05-19 14:58:00 +0300 EEST 2020-05-19 14:57:00 +0300 EEST 0x8573e0 0x8573e0}]
`

**and old + new crons:**

`2020/05/19 14:57:47 Crons after start [{1 0xc0000c8240 2020-05-19 14:58:00 +0300 EEST 2020-05-19 14:57:00 +0300 EEST 0x8573e0 0x8573e0} {2 0xc0000c8280 2020-05-19 14:58:00 +0300 EEST 2020-05-19 14:57:00 +0300 EEST 0x8573e0 0x8573e0} {3 0xc0000c82c0 2020-05-19 14:58:00 +0300 EEST 2020-05-19 14:57:00 +0300 EEST 0x8573e0 0x8573e0} {4 0xc000624c80 2020-05-19 14:58:00 +0300 EEST 0001-01-01 00:00:00 +0000 UTC 0x8573e0 0x8573e0} {5 0xc000624cc0 2020-05-19 14:58:00 +0300 EEST 0001-01-01 00:00:00 +0000 UTC 0x8573e0 0x8573e0} {6 0xc000624d40 2020-05-19 14:58:00 +0300 EEST 0001-01-01 00:00:00 +0000 UTC 0x8573e0 0x8573e0}]`

So finaly i have something to remove.. 

But still strange that when Crons where created in other function then they just disapeared in "Entries()", but they were still running in background.

**Comment by xiongjing825** [comment]
1. 2023-12-14，i  meet this problem also
2. sometimes Remove   function don‘t  make effect 
3. and  i have read code ,  but  get no reason.
