### ISSUE TITLE
q: what does `time.Now().Local()` do?

### ISSUE THREAD

**Issue by dvdplm** [robfig/cron#32]
This might be the wrong venue and perhaps a dumb question, but what is the reason for calling `Local()` on `time.Now()`? I see it e.g. here: https://github.com/robfig/cron/blob/v2/cron.go#L164

Thanks!

**Comment by robfig** [comment]
That gets the time in the local time of the machine rather than UTC.  crontabs are written against the machine time, so that is necessary to interpret them correctly
