### ISSUE TITLE
Should we wait until the previous running job is finished?

### ISSUE THREAD

**Issue by woodpenker** [robfig/cron#329]
If I set the cron to execute some job every second, but this job takes 5 seconds to finished. What I want is at any time there only exists one running job, but what I get is 5 or 4 jobs running parallel at the same time. Should we check the previous job running status to avoid running another goroutine before the previous goroutine is finished? 
Blew is the test code:
```go
c := cron.New()
c.AddFunc("*/1 * * * *", func() {
	fmt.Println(runtime.NumGoroutine())
	time.Sleep(5 * time.Second)
})
c.Start()
```
It output like this:
```
3
4
5
6
7
8
8
8
...
```
5 same goroutine is created after running for 5 seconds,  after that, one goroutine is created to wait for 5s, one is finished and 5 same exist.

**Comment by rissw** [comment]
i think you should do your own check (whether the previous job is running or not) if you want only single job running.
maybe something like this:
```go
package main

import (
	"fmt"
	"runtime"
	"sync"
	"time"

	"github.com/robfig/cron/v3"
)

func main() {
	c := cron.New(cron.WithSeconds())
	_, err := c.AddFunc("*/2 * * * * *", func() {
		fmt.Println(">>>>>>>>> Num goroutine:", runtime.NumGoroutine())

	})
	if err != nil {
		panic(err)
	}
	c.Start()

	mf := &myFunc{job: 1}
	job := cron.New(cron.WithSeconds())
	_, err = job.AddFunc("*/1 * * * * *", mf.run)
	if err != nil {
		panic(err)
	}
	job.Start()

	wait := make(chan struct{})
	<-wait
}

type myFunc struct {
	mtx       sync.Mutex
	isRunning bool
	job       int
}

func (m *myFunc) SetRun() bool {
	m.mtx.Lock()
	defer m.mtx.Unlock()

	if m.isRunning {
		return false
	}

	m.isRunning = true
	return true
}

func (m *myFunc) doneRun() {
	m.mtx.Lock()
	m.isRunning = false
	defer m.mtx.Unlock()
}

func (m *myFunc) run() {
	if !m.SetRun() {
		fmt.Printf("Job #%d still running\n", m.job)
		return
	}
	fmt.Println("Running job:", m.job)
	time.Sleep(5 * time.Second)
	m.job++
	m.doneRun()
}
```

**Comment by woodpenker** [comment]
Yes, of cause I can do the limit with `mutex`, but It may be strange for people who are not sure how long the jobs take to finish, they may suppose the job will run only one instance at any time. If the job is not idempotent, the result will be wrong. So I am asking whether it is necessary to ensure this inside, or give a choice to the user to let them choose how to act.

**Comment by rissw** [comment]
IMHO, since this is a package which works similar to a linux/unix crontab, let it be....user should be aware of what he/she's doing and manage the code accordingly,whether using mutex, context, etc

**Comment by woodpenker** [comment]
OK, get it. But for some situation crontab is not the silver bullet, users need to care about it when using this package. Thanks for explaining. I will close this issue.
