### ISSUE TITLE
Incorrectly handles subsecond durations

### ISSUE THREAD

**Issue by EmilLaursen** [robfig/cron#334]
Thank you for this library.

I may have encountered a small bug. I have been using the "@every X" syntax in some tests, with small duration intervals, i.e. ns, us, and ms. It appears that the library can not handle anything below the 1second threshold.

Indeed, it appears that any subsecond interval will default to ticking every second. Here is a playground snippet, which runs 4 tests, that illustrates the issue:

https://play.golang.org/p/Ce7DB_AueKV

Every test ticks the same amount of times, which is not what I expect! Let me know if you need more information.

**Comment by buildscientist** [comment]
@EmilLaursen 

Not a bug considering the [documentation](https://godoc.org/github.com/robfig/cron#Every) very clearly states that "@every" doesn't handle a duration of less than a second. 

If you're looking for subsecond intervals you're probably better off implementing using Golang's built in [ticker](https://gobyexample.com/tickers) which does support sub-second durations.

**Comment by EmilLaursen** [comment]
Ah, I see. I should have RTFM :) Thanks again.
