### ISSUE TITLE
Cron doesn't work, please help me

### ISSUE THREAD

**Issue by luojuan822** [robfig/cron#338]
Here is the thing. If i build the project with commend: go build statistics.go, then the cron has work well. But if I build the project with command: CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -installsuffix cgo -o statistics statistics.go,
And then the cron didn't work any more. please help me out.

**Comment by luojuan822** [comment]
`import (
	"database/sql"
	_ "github.com/go-sql-driver/mysql"
	"github.com/golang/glog"
	"github.com/robfig/cron"
	"statistics/config"
	"statistics/util"
	"statistics/vo"
	"strings"
	"sync"
	"time"
)

type StatisticsService struct {
	GisDB util.GisWriteDB 		"inject"
	StatDB util.StatDB 			"inject"
}

var statisticsService StatisticsService;
func init() {
	glog.Info("statisticsService init ")
	statisticsService = StatisticsService{}
	config.SetService(&statisticsService)

	statisticsService.InitTask()
}

func (service *StatisticsService) InitTask()  {
	glog.Info("statisticsService InitTask begin ")
	c := cron.New()
	c.AddFunc("0 55 10 * * *", func() {//"0 0 1 * * *"
		service.SyncSysOffice()
		day := time.Now().AddDate(0, 0, -1)
		service.runAllTask(day)
		userStatisticsService.RunDayMemberData(day)
	})
	c.AddFunc("0 5 * * * *", func() {//"0 0 1 * * *"

		h, _ := time.ParseDuration("-1h")
		beginTime, endTime := service.getHourTime2(time.Now().Add(h))
		service.runHourAllTask(beginTime, endTime)
	})
	c.Start()
	glog.Info("statisticsService InitTask end ")
}`

**Comment by robfig** [comment]
What error do you see?

**Comment by luojuan822** [comment]
No error was printed. I solved this by upgrade go version from 1.11 to 1.14. Thank you so much!
