### ISSUE TITLE
print cron logs to file

### ISSUE THREAD

**Issue by mkloveyy** [robfig/cron#339]
How to print logs of cron jobs into a file such as "/var/log/cron.log"?

**Comment by buildscientist** [comment]
@mkloveyy Have a look at the[ option.WithLogger()](https://godoc.org/github.com/robfig/cron#WithLogger). When you create an instance of cron you can pass WithLogger as option. 

Example: 
``` go 
//Note the user running the go process/binary needs to have permissions to read/write to this file
logFile,err := os.Open("/var/log/cron.log") 

if err != nil {
  //Handle error
}
kron := cron.New(cron.VerbosePrintfLogger(log.New(logFile, "cron: ", log.LstdFlags))))
```

**Comment by robfig** [comment]
Exactly^ 

Thanks @buildscientist
