### ISSUE TITLE
A small bug when using c.AddFunc after c.Start

### ISSUE THREAD

**Issue by qiukeren** [robfig/cron#34]
when using 

```
c:=cron.New()
c.Start()
time.Sleep(5*time.Second)
c.AddFunc("* * * * * *",myfunc)
```

the myfunc is
```
func myfunc(){
fmt.Println(time.Unix(time.Now().Unix(), 0).Format("2006-01-02 15:04:05"))
```

the output is:(current time is 15:16:07)
```
2015-11-23 15:16:07  <- first in sleep 5
2015-11-23 15:16:07  <- 2nd in sleep 5
2015-11-23 15:16:07  <- 3rd in sleep 5
2015-11-23 15:16:07  <- 4th in sleep 5
2015-11-23 15:16:07  <- 5th in sleep 5
2015-11-23 15:16:07  <- truely the first second
2015-11-23 15:16:08  <- truely the second second
2015-11-23 15:16:09  <- truely the third second
```

However,modify `cron.go`  from 

```
// Run the scheduler.. this is private just due to the need to synchronize
// access to the 'running' state variable.
func (c *Cron) Run() {
	// Figure out the next activation times for each entry.
	now := time.Now().Local()
	for _, entry := range c.entries {
		entry.Next = entry.Schedule.Next(now)
	}

	for {

		// Determine the next entry to run.
		sort.Sort(byTime(c.entries))
```

To

```
// Run the scheduler.. this is private just due to the need to synchronize
// access to the 'running' state variable.
func (c *Cron) Run() {
	// Figure out the next activation times for each entry.
-	now := time.Now().Local()                                 <--------------assigned 'new' before the for loop
-	for _, entry := range c.entries {                      
-		entry.Next = entry.Schedule.Next(now)
-	}                                                                     

	for {
+		now := time.Now().Local()                     
+		for _, entry := range c.entries {              
+			entry.Next = entry.Schedule.Next(now) 
+		}                                                                      

		// Determine the next entry to run.
		sort.Sort(byTime(c.entries))
```

may solve this problem.

**Comment by qiukeren** [comment]
The upper is [a small modification](https://github.com/runner-mei/cron) of robfig/cron ,which can assign the cron `entryid` one self(it's useful to me).

**Comment by elgs** [comment]
You code won't compile. I guess you wanted to say `c:=cron.New()`. Also did you mean to let the code sleep 5 milliseconds or 5 seconds?

**Comment by qiukeren** [comment]
@elgs sorry sir.

it's time.Sleep(5*time.Second)

**Comment by qiukeren** [comment]
@elgs 
A full demo is here:(the upper is just extracted from my project so it is incomplete)
工程代码不太好泄露，下面是刚刚写的完整的测试：

```
$ cat a.go 
package main

import (
	"fmt"
	"gopkg.in/robfig/cron.v2"
	"time"
)

func main() {
	c := cron.New()
	c.Start()
	time.Sleep(5 * time.Second)
	c.AddFunc("* * * * * *", myfunc)
	select {}
}

func myfunc() {
	fmt.Println(time.Unix(time.Now().Unix(), 0).Format("2006-01-02 15:04:05"))
}
```


```
$ go run a.go 
2015-11-23 17:49:40  <-sleep 1
2015-11-23 17:49:40  <-sleep 2
2015-11-23 17:49:40  <-sleep 3
2015-11-23 17:49:40  <-sleep 4
2015-11-23 17:49:40  <-sleep 5
2015-11-23 17:49:41 第一秒
2015-11-23 17:49:42 第二秒
```



另外，如果中途停掉这个任务，然后再启动的话，效果也是（任务会把被停止的时间遍历一遍，多到几十秒少到几秒都是这样。）

**Comment by elgs** [comment]
It looks like you are running a modified version of cron. 

Here is my test code:

```golang
package main

import (
	"fmt"
	"github.com/robfig/cron"
	"time"
)

func main() {
	myfunc()
	fmt.Println("Run!")
	c := cron.New()
	c.Start()
	time.Sleep(5 * time.Second)
	c.AddFunc("* * * * * *", myfunc)
	select {}
}
func myfunc() {
	fmt.Println(time.Unix(time.Now().Unix(), 0).Format("2006-01-02 15:04:05"))
}
```
And here is the output:

```
2015-11-23 01:55:45
Run!
2015-11-23 01:55:50
2015-11-23 01:55:50
2015-11-23 01:55:50
2015-11-23 01:55:50
2015-11-23 01:55:50
2015-11-23 01:55:51
2015-11-23 01:55:52
2015-11-23 01:55:53
2015-11-23 01:55:54
```

The result seems to look good to me.

**Comment by qiukeren** [comment]
`2015-11-23 01:55:50`

The problem is, at this second,the function was repeated five times.
(In my opinion, the function should start at `2015-11-23 01:55:51`)

**Comment by elgs** [comment]
After spending 2 hours loading everything back into my brain, I'm pretty sure this is a bug. The bug is triggered if the duration (`t seconds`) between the time `c.Start()` and the first `c.AddFunc()` is longer than 1 second (since Next() resolution is 1 second), the `entry.Next` doesn't have a chance to be updated, so `effective` remains outdated, causing `c.Next` being called multiple times (`t` times) to catch up. Each invocation of `e.Next = e.Schedule.Next(effective)` moves `e.Next` and `effective` one second forward.

**Comment by elgs** [comment]
@robfig, have you had a chance to take a look at this issue? I don't think it's a small bug, especially in the use cases where jobs are added sometime after cron `Start`ed?

**Comment by robfig** [comment]
Ah, good catch. I wonder if it's possible to avoid re-sorting on every iteration; maybe it would be sufficient to sort initially and when jobs are added? 

Thank you!

**Comment by elgs** [comment]
I think re-sorting on every iteration is necessary, unless all jobs follow the same cron spec. A monthly job at the top of the queue after its run might just fall to the tail of the queue.

**Comment by robfig** [comment]
OK, makes sense.

**Comment by qiukeren** [comment]
你们肯定有基情……

**Comment by tdterry** [comment]
I'm running into what I think is the same issue. It seems the problem comes from cron.go line 167 where the new entry is scheduled. It should be using a fresh "now" (time.Now().Local()) rather than the cached "now"
