### ISSUE TITLE
[Question] Is this "every 2 weeks" cronjob format going to work? 

### ISSUE THREAD

**Issue by RizkiHerdaID** [robfig/cron#345]
I was looking for cron to run every 2 weeks and I found it here:
https://cron.help/every-2-weeks

Picture without command section
![image](https://user-images.githubusercontent.com/6695499/95308612-56e64880-08b4-11eb-913c-5ed9cdb9c221.png)

Is this going to work on this package?

**Comment by rohmanhm** [comment]
@RizkiHerdaID, I hope this is helpful. https://cron.help/questions#every-two-weeks

**Comment by robfig** [comment]
Exactly^  

Thanks @rohmanhm
