### ISSUE TITLE
Panic if stop is called before start

### ISSUE THREAD

**Issue by bruth** [robfig/cron#35]
This was obviously an error on my part, but discovered that calling `Stop` without calling `Start` will block since nothing is receiving [`c.stop <- struct{}{}`](https://github.com/robfig/cron/blob/master/cron.go#L183). This is definitely a programmer error, I suggest panicking if the cron is not running.

```go
// Stop the cron scheduler.
func (c *Cron) Stop() {
	if !c.running {
		panic("cron: not running")
	}
	c.stop <- struct{}{}
	c.running = false
}
```

**Comment by elgs** [comment]
`panic` will cause the process to quit. I think it's overkilling for a server program to quit if the admin click the wrong button.

**Comment by bruth** [comment]
> I think it's overkilling for a server program to quit if the admin click the wrong button.

The assumption here is that given a UI where you can start or stop a cron schedule. A more fundamental issue is that there is no way to checking if a cron is running, i.e. `c.running` is not accessible. If `c.Running()` was added, then clicking the wrong button could be guarded. I still think that it is incorrect to call `Stop` without calling `Start` since if it silently returns, then the programmer may miss the fact that it was never running to begin with.

**Comment by elgs** [comment]
Right, but it's still not a library's responsibility to quit my process. The library should just tell me what happened, and I will decide what to do.

**Comment by bruth** [comment]
> The library should just tell me what happened, and I will decide what to do.

Fair enough. So then the alternative would be for `Stop` to return an error such as `ErrNotRunning`?

**Comment by elgs** [comment]
> Fair enough. So then the alternative would be for Stop to return an error such as ErrNotRunning?

Agreed. That would be the most appropriate way.

**Comment by robfig** [comment]
I think it would be ok if it also silently did nothing.  Happy to accept a PR for this!

**Comment by bruth** [comment]
> I think it would be ok if it also silently did nothing. Happy to accept a PR for this!

@robfig Happy to. Would you prefer that so it would be backwards compatible change?

**Comment by shurcooL** [comment]
It's worth pointing out that adding a single return value to a func that previously returned nothing happens to be a strictly backwards compatible change.

**Comment by robfig** [comment]
Just didn't seem like anyone would care to check it and do something different. Usually returning an error implies that the operation wasn't done, but in this case the end state is the desired one.

**Comment by shurcooL** [comment]
Yeah, I am in agreement.

**Comment by bruth** [comment]
So if I am not mistaken #36 adds the desired change.
