### ISSUE TITLE
go.mod compatibility

### ISSUE THREAD

**Issue by febytanzil** [robfig/cron#350]
hi, I face this issue when my project is using go.mod, since I'm using v3+

> require github.com/robfig/cron: version "v3.0.1" invalid: module contains a go.mod file, so major version must be compatible: should be v0 or v1, not v3

I think it's related how go mod requirement on how it should named if the version is above v1
https://golang.org/cmd/go/#hdr-Module_compatibility_and_semantic_versioning

would you consider to update the version? thanks.

**Comment by pkopac** [comment]
@febytanzil It happened to me as well, because I skipped the README about v3 :)
Important parts:
Make sure you import the library like this:
`import (cron "github.com/robfig/cron/v3")`
and that you have `github.com/robfig/cron/v3` in `go.mod`, NOT `github.com/robfig/cron`

**Comment by robfig** [comment]
Exactly^ 

Thanks
