### ISSUE TITLE
Modify the schedule time dynamically for the same job

### ISSUE THREAD

**Issue by FunkyYang** [robfig/cron#353]
someone help?

**Comment by sds123go** [comment]
How to do that ?

**Comment by robfig** [comment]
Sorry, this is not possible. You would have to `Remove` and `Add`

**Comment by heaxo** [comment]
@robfig Best regards：How should I implement Remove, it seems that there is no method provided for Remove, Stop is not Remove, right?

**Comment by janrnc** [comment]
There is a `Remove` method.

https://github.com/robfig/cron/blob/bc59245fe10efaed9d51b56900192527ed733435/cron.go#L203-L212
