### ISSUE TITLE
Add special handler for sub minute granularity

### ISSUE THREAD

**Issue by ivanjaros** [robfig/cron#360]
From the docs it seems there is support for sub-minute scheduler but it requires a different setup.
It would be better, DX-wise, to have just another method, like AddJobSeconds([seconds value], Job) to make it easily usable.

**Comment by skowrons** [comment]
What is so problematic to just use `cron.New(cron.WithSeconds())`'?

**Comment by robfig** [comment]
I think that there's benefit in having a smaller API, even if it requires some additional ceremony. Personally, I appreciate how the Go standard library generally has much smaller interfaces than (most of) the JDK, which has overlapping methods in an attempt to make more use cases read like English. Reasonable people could disagree on that, though.

`AddJobSeconds` would be a pretty specialized addition, which I would prefer to avoid. Thanks for the suggestion though
