### ISSUE TITLE
Cron does not respect day of week if complex day of months are set

### ISSUE THREAD

**Issue by zahiar** [robfig/cron#368]
I've come across a possible bug whereby I'm trying to run a cron every 2 weeks on a Monday but when I configure the day of months, the cron no longer respects the day of week and runs every day. Looks like day of month takes precedence or something.

With today being the 12th, this doesn't run & rightly so.
`* * 1-7,15-21 * MON`

However, this does run as the date range is within the day of month specified but it's not Monday.
`* * 8-14,22-28 * MON`

**Comment by mattcarmody** [comment]
I'm new to the package so I can't address the potential bug but just want to point out that this isn't quite a schedule to run every 2 weeks, it's to run the second and fourth Monday of every month.

Here's a related issue for doing every other week: #345 . However, looking around the package it looks like using a constant delay schedule could be appropriate for your use case: https://github.com/robfig/cron/blob/master/constantdelay.go

**Comment by zahiar** [comment]
Thanks, I was aiming for the cron to run on every other Monday & I've managed to do that like so:
```
	c.AddFunc("0 0 1-7,15-21 * *", func() {
		if time.Now().Weekday().String() == "Monday" {
			runSomeCommand(a, b)
		}
	})
```

That was after I read/found this:
> Note: The day of a command's execution can be specified by two fields --
> day of month, and day of week. If both fields are restricted (ie, are
> not *), the command will be run when either field matches the current
> time. For example, ``30 4 1,15 * 5'' would cause a command to be run at
> 4:30 am on the 1st and 15th of each month, plus every Friday.

**Comment by mattcarmody** [comment]
I'm still not sure that will run every other Monday all year. It seems it will miss consecutive Mondays in months when a Monday falls on the 29th, 30th or 31st of the month.

**Comment by skowrons** [comment]
I think this is totally normal behavior. If you move your configuration into [crontab.guru](https://crontab.guru/) you will see all runs of that particular job. 

https://crontab.guru/#0_0_1-7,15-21_*_MON

As stated by crontab your job will run on the days 1-7, 15-21 AND on Mondays. And I really think there is no way to run a job every two weeks only for Monday. 
So this isn't a bug, but rather the expected behavior.

**Comment by zahiar** [comment]
Okie dokie, thanks for the reply :)
Yeah, with that IF statement in my code example earlier, all is well.
