### ISSUE TITLE
The process has been killed, but the timer task is still running?

### ISSUE THREAD

**Issue by Huangsh17** [robfig/cron#369]
The process has been killed, but the timer task is still running?

**Comment by skowrons** [comment]
If you kill the main process all goroutines like the timer will als be terminated.

**Comment by robfig** [comment]
I would need a reproducer to investigate this. I don't see how it's possible, though. The cron library does not fork or exec anything, nor catches any signals. I don't see how this could be related, other than it makes it not obvious that the program is still running and will wake up in the future. Please re-open if you can reproduce. Thanks
