### ISSUE TITLE
Cron week number dismatched

### ISSUE THREAD

**Issue by fwhezfwhez** [robfig/cron#371]
The last letter of cron spec, in this package
0 - Sun
1 - Mon
...
6 - SAT

But I refer to websites, all references are talking 
1-SUN
2-MON
...
7-SAT

What is the true standard of it?

**Comment by skowrons** [comment]
There is no true standard for cron. Cron is just a system for defining the execution of a job in a given time interval. The first UNIX implementation used 0-6. So you can say this is the standard, and it is the system used in this library.

In the end every one who implements a cron scheduler can define the spec as they want.

**Comment by fwhezfwhez** [comment]
3q
