### ISSUE TITLE
Cron not work in every 5 minutes

### ISSUE THREAD

**Issue by muhfaris** [robfig/cron#373]
I use robfig/cron version 3 `"github.com/robfig/cron/v3"`

My cron expression is `5 * ? * ?`, I want to run a job every 5 minutes in every day.
this sample how to I used:
`c.AddFunc("5 * ? * ?", func() { fmt.Println("every 5 minute")}`

I wait 10 minutes for it, but nothing happens. What's wrong with my expression?

**Comment by mozillazg** [comment]
@muhfaris How about change the cron expression to 

```
*/5 * * * *
```

**Comment by muhfaris** [comment]
Hi @mozillazg , thanks for your reply

Yeah, I can use it. But I have another problem.
In my case, I want to use the expression `*/5 * * * *`, because it's customized then `@every 5m`.
I compare it at the same time, but the cron expression `*/5 * * * *` not correctly.

this log of both:
Running at `22:04:43`:

My expectation the cron will be running at `22:09:43`, `22:14:43`, `22:18:43`
But the cron runnint at:

log of `*/5 * * * *`:
```
22:05:00.000241233 +0700 WIB m=+16.599573856
22:10:00.000532559 +0700 WIB m=+316.599865185
22:15:00.000225446 +0700 WIB m=+616.599558195
```

log of `@every 5m`:
```
22:09:43.000748958 +0700 WIB m=+299.600081672
22:14:43.000339916 +0700 WIB m=+599.599672588
22:19:43.000391915 +0700 WIB m=+899.599724603
```

They both express the same goal, but why different results? the running properly just only `@every 5m`.

**Comment by mozillazg** [comment]
@muhfaris They are different:

* `*/5 * * * *`: run the job at **every 5th minute**: 
	> Note: It is also possible to specify */n to run for every n-th interval of time.
	https://en.wikipedia.org/wiki/Cron#Overview
* `@every 5m`: run the job **after 5 minutes, then every 5 minutes** after that: https://github.com/robfig/cron/blob/6a8421bcff44c2a9889075724070baaebf8dcd72/doc.go#L130-L135

**Comment by muhfaris** [comment]
@mozillazg so, how to implement `@every 5m` in cron expression format?

**Comment by mozillazg** [comment]
@muhfaris Looks like there is no way to implement it via cron expression.

https://github.com/robfig/cron#background---cron-spec-format

**Comment by muhfaris** [comment]
okay @mozillazg 
do you have a suggestion to implement cron in every 5 minutes based current time?

**Comment by skowrons** [comment]
@muhfaris your implementation would look like this:

```go
func main() {
	c := cron.New()
	c.AddFunc("@every 5m", func() {
		log.Println("hello 5")
		log.Println(time.Now())
	})
	c.Run()
}
```

The [part of the docu explaining exactly that.](https://github.com/robfig/cron/blob/bc59245fe10efaed9d51b56900192527ed733435/doc.go#L26)

**Comment by skowrons** [comment]
Just use `@every 5m`. It is based current time as @mozillazg explained.

```go
func main() {
	c := cron.New()
	c.AddFunc("@every 5m", func() {
		log.Println("hello 5")
		log.Println(time.Now())
	})
	c.Run()
}
```
