### ISSUE TITLE
Cron schedule for sunday is not working

### ISSUE THREAD

**Issue by snehalborse** [robfig/cron#377]
Usage:
I'm using package **"github.com/robfig/cron/v3"** to validate a cron schedule string. 

Problem:
When I give input as "0 0 * * 0" (for weekly) it returns with error saying **invalid schedule**.
As per [your document](https://github.com/robfig/cron#upgrading-to-v3-june-2019), v3 supports the standards as per [cron wiki page](https://en.wikipedia.org/wiki/Cron).

This cron schedule was working fine few days ago but has started giving error recently.

Expected outcome:
The string should be considered as valid and the code should proceed.

**Comment by skowrons** [comment]
@snehalborse can you please provide any code or system information? I can't really reproduce your problem on my side.
My try to reproduce your problem:
```go
func main() {
        c := cron.New()
	_, err := c.AddFunc("0 0 * * 0", func() {})
	if err != nil {
		log.Println(err)
	}
	c.Run()
}
```

**Comment by snehalborse** [comment]
Hi @skowrons below is the code snippet I'm trying with
```
import "github.com/robfig/cron/v3"
...
func ValidateCronSchedule(schedule string) error {
	_, err := cron.Parse(schedule)
	if err != nil {
                 printf("Invalid schedule '%s'", schedule)
	}
}
```

**Comment by snehalborse** [comment]
However when I give a try using cron.ParseStandard it accepted **"0 0 * * 0"**
Can you confirm if this is correct? As per the [documentation](https://pkg.go.dev/github.com/robfig/cron#ParseStandard) I see, it is a way to  validate standard cron schedule mentioned in [wiki](https://en.wikipedia.org/wiki/Cron).
I'm just wondering why it worked with Parse earlier and not working now. Can you clarify this?

**Comment by skowrons** [comment]
First when you use v3 you should use the correct [dokumentation](https://pkg.go.dev/github.com/robfig/cron/v3). 

I can reproduce your problem but only for version v1.2.0. It seems the Problem is the zero of the day of week part. 

@snehalborse you importing v3 but how are you able to use `cron.Parse()` this was removed with v3?

**Comment by snehalborse** [comment]
@skowrons I used parse as given here: https://pkg.go.dev/github.com/robfig/cron/v3#Parser.Parse which is there in v3 documentation as well. Can you point out the documentation where it confirms that `cron.Parse()` is deprecated/removed?

I'm able to validate my cron schedule with `cron.ParseStandard()`. Can you confirm if `cron.ParseStandard()` is the correct way to validate 5 field cron schedule (as per [wiki](https://en.wikipedia.org/wiki/Cron))?

This is my working code snippet:
```
import "github.com/robfig/cron/v3"
...
func ValidateCronSchedule(schedule string) error {
	_, err := cron.ParseStandard(schedule)
	if err != nil {
                 printf("Invalid schedule '%s'", schedule)
	}
}
```

**Comment by skowrons** [comment]
I can confirm your solution is working. 
```go
schedule := "0 0 * * 0"
_, err := cron.ParseStandard(schedule)
if err != nil {
	log.Printf("Invalid schedule '%s'", schedule)
}
```

I meant that the standalone global function Parse() dosen't exist anymore. It is only usable with the Parser struct. But that dosen't explain your error. Maybe there was an error in your the ParseOptions?

Somethin like this should work exactly the same like the standard parser:
```go
schedule := "0 0 * * 0"
parser := cron.NewParser(cron.Minute | cron.Hour | cron.Dom | cron.Month | cron.Dow)
_, err := parser.Parse(schedule)
if err != nil {
	log.Printf("Invalid schedule '%s'", schedule)
}
```

**Comment by G2G2G2G** [comment]
I've had this running for like 2 years and it works fine:
```Go
c := cron.New()
c.AddFunc("0 10,20 * * 0,6", myfunchere)
c.Start()
```
(there are like 50 other tasks, I cut those out
also Start() is correct, not run().......

**Comment by robfig** [comment]
Sounds like this was due to the move to the standard spec, which omits seconds as a field by default. Sorry for that hassle, but I'm glad everything got worked out. Thanks for helping in my absence @skowrons
