### ISSUE TITLE
Cannot have the function triggered 

### ISSUE THREAD

**Issue by afzalabbasi** [robfig/cron#378]
i am using following code 

go func() {
		cr := cron.New()
		_, err := cr.AddFunc("@every 5s", func() {
			logrus.Errorln("cron trigger")
			
		})
		if err != nil {
			logrus.Errorln(err.Error())
			//panic(err)
		}
		cr.Start()
		//defer cr.Stop()
	}()
when i commit defer cr.stop part its working fine cron trigger after every 5 min but with defer cr.stop  cron does not trigger.
can anyone please explain this why this happen .

**Comment by skowrons** [comment]
When you use `Start()` the cron scheduler will start its own goroutine. So it will continue with the following instruction in your function. If there aren't any left it will call defer and the `Stop()` function. So your scheduler will be terminated. If you still want your solution just use `Run()`. `Run()` won't start a new goroutine so your defer clause is not executed immediately.

```go
func main() {
	go func() {
		cr := cron.New()
		_, err := cr.AddFunc("@every 5s", func() {
			log.Println("cron trigger")
		})
		if err != nil {
			log.Println(err.Error())
		}
		cr.Run()
		defer cr.Stop()
	}()
	select{}	
}
```

**Comment by afzalabbasi** [comment]
thanks
now its working

**Comment by skowrons** [comment]
@afzalabbasi please close the issue if it's resolved.
