### ISSUE TITLE
Calculate next trigger time from crontab-like string

### ISSUE THREAD

**Issue by bobc82** [robfig/cron#388]
Is there a method to calculate simply next execution time from a crontab-like string?

For example, the input is:

`*/5 * * * *`

And the output should be, at the moment that i'm writing:

2021-04-21 17:55:00

An illustrative example can be viewed here:

`https://crontab.guru/#*/5_*_*_*_*`

**Comment by wishdev** [comment]
ParseStandard or Parser.Parse along with Next will do the job

For example

```
package main

import (
	"fmt"
	cron "github.com/robfig/cron/v3"
	"time"
)

func main() {
	sched, _ := cron.ParseStandard("*/5 * * * *")
	fmt.Println(sched.Next(time.Now()))
}
```

**Comment by robfig** [comment]
Exactly^ 

Thanks @wishdev !
