### ISSUE TITLE
I would like to start an hourly task in eight hours

### ISSUE THREAD

**Issue by lx217197** [robfig/cron#398]
what should i do?

**Comment by ganehag** [comment]
Something like this maybe?

```go
c := cron.New()

// Start the scheduler
c.Start()

// Some go func with the sole purpose 
// of waiting 8 hours before adding an hourly job
go func(c *cron.Cron) {
	// Wait 8 hours
	<-time.After(8 * time.Hour)

	c.AddFunc("@hourly",      func() { fmt.Println("Every hour") })
}(c)
```

**Comment by lx217197** [comment]
In fact, I wanted to have a @ delay function, but I implemented it in my own way

type StartDelaySchedule struct {
	immediate     bool
	schedule      cron.Schedule
	delayDuration time.Duration
}

func NewDelaySchedule(spec string, delay string, immediate bool) (*StartDelaySchedule, error) {
	delayDuration, _ := time.ParseDuration(delay)

	schedule, err := cron.ParseStandard(spec)
	if err != nil {
		return nil, err
	}
	return &StartDelaySchedule{schedule: schedule, delayDuration: delayDuration, immediate: immediate}, nil
}

func (schedule *StartDelaySchedule) Next(t time.Time) time.Time {
	defer func() {
		schedule.delayDuration = 0
		schedule.immediate = false
	}()
	if schedule.immediate == false {
		return schedule.schedule.Next(t.Add(schedule.delayDuration))
	}
	return t.Add(schedule.delayDuration)

}

**Comment by lx217197** [comment]
In fact, I wanted to have a @ delay function, but I implemented it in my own way


type StartDelaySchedule struct {
	immediate     bool
	schedule      cron.Schedule
	delayDuration time.Duration
}

func NewDelaySchedule(spec string, delay string, immediate bool) (*StartDelaySchedule, error) {
	delayDuration, _ := time.ParseDuration(delay)

	schedule, err := cron.ParseStandard(spec)
	if err != nil {
		return nil, err
	}
	return &StartDelaySchedule{schedule: schedule, delayDuration: delayDuration, immediate: immediate}, nil
}

func (schedule *StartDelaySchedule) Next(t time.Time) time.Time {
	defer func() {
		schedule.delayDuration = 0
		schedule.immediate = false
	}()
	if schedule.immediate == false {
		return schedule.schedule.Next(t.Add(schedule.delayDuration))
	}
	return t.Add(schedule.delayDuration)

}

**Comment by lx217197** [comment]
> Something like this maybe?
> 
> ```go
> c := cron.New()
> 
> // Start the scheduler
> c.Start()
> 
> // Some go func with the sole purpose 
> // of waiting 8 hours before adding an hourly job
> go func(c *cron.Cron) {
> 	// Wait 8 hours
> 	<-time.After(8 * time.Hour)
> 
> 	c.AddFunc("@hourly",      func() { fmt.Println("Every hour") })
> }(c)
> ```

In fact, I wanted to have a @ delay function, but I implemented it in my own way

`

type StartDelaySchedule struct {
	immediate     bool
	schedule      cron.Schedule
	delayDuration time.Duration
}

func NewDelaySchedule(spec string, delay string, immediate bool) (*StartDelaySchedule, error) {
	delayDuration, _ := time.ParseDuration(delay)

	schedule, err := cron.ParseStandard(spec)
	if err != nil {
		return nil, err
	}
	return &StartDelaySchedule{schedule: schedule, delayDuration: delayDuration, immediate: immediate}, nil
}

func (schedule *StartDelaySchedule) Next(t time.Time) time.Time {
	defer func() {
		schedule.delayDuration = 0
		schedule.immediate = false
	}()
	if schedule.immediate == false {
		return schedule.schedule.Next(t.Add(schedule.delayDuration))
	}
	return t.Add(schedule.delayDuration)

}
`

**Comment by lx217197** [comment]
> Something like this maybe?
> 
> ```go
> c := cron.New()
> 
> // Start the scheduler
> c.Start()
> 
> // Some go func with the sole purpose 
> // of waiting 8 hours before adding an hourly job
> go func(c *cron.Cron) {
> 	// Wait 8 hours
> 	<-time.After(8 * time.Hour)
> 
> 	c.AddFunc("@hourly",      func() { fmt.Println("Every hour") })
> }(c)
> ```

In fact, I wanted to have a @ delay function, but I implemented it in my own way

`
type StartDelaySchedule struct {
	immediate     bool
	schedule      cron.Schedule
	delayDuration time.Duration
}

func NewDelaySchedule(spec string, delay string, immediate bool) (*StartDelaySchedule, error) {
	delayDuration, _ := time.ParseDuration(delay)

	schedule, err := cron.ParseStandard(spec)
	if err != nil {
		return nil, err
	}
	return &StartDelaySchedule{schedule: schedule, delayDuration: delayDuration, immediate: immediate}, nil
}

func (schedule *StartDelaySchedule) Next(t time.Time) time.Time {
	defer func() {
		schedule.delayDuration = 0
		schedule.immediate = false
	}()
	if schedule.immediate == false {
		return schedule.schedule.Next(t.Add(schedule.delayDuration))
	}
	return t.Add(schedule.delayDuration)

}`

**Comment by ganehag** [comment]
OK. Then this issue should be closed.
