### ISSUE TITLE
Question - sequencing

### ISSUE THREAD

**Issue by joeblew99** [robfig/cron#40]
Is it possible to sequence a job to start after another job has finished ?
You never know how long the first job will take.
This might be an anti - pattern I know, because sequences and timed jobs are really opposites, but worth asking.

Thanks in advance for this library

**Comment by robfig** [comment]
One way would be to create a "SerialJob" wrapper that accepts multiple jobs and runs them in series. I think the key is that cron is the thing that triggers on a schedule, but everything that happens afterwards can be done with wrappers around Job.
