### ISSUE TITLE
Why there is a break statement at the end of a for loop ?

### ISSUE THREAD

**Issue by dushaoshuai** [robfig/cron#400]
https://github.com/robfig/cron/blob/ccba498c397bb90a9c84945bbb0f7af2d72b6309/cron.go#L262
```golang
for {
	select {
	case now = <-timer.C:
		...
	case newEntry := <-c.add:
		...
	case replyChan := <-c.snapshot:
		...
	case <-c.stop:
		...
	case id := <-c.remove:
		...
	}
	break
}
```
I'm very confused about this for loop. Why there is a break statement at the end of the loop ? Can anybody give me a hint ?

**Comment by hanagantig** [comment]
I guess this break should stop inner loop after timer activation case to set new timer in outer loop. Otherwise, you will reach first case just once.

**Comment by mostafa-asg** [comment]
If no case matches, it breaks. If `case replyChan := <-c.snapshot:` matches, the `select` statement executes again.

**Comment by robfig** [comment]
Exactly ^ 

The goal is to process any pending messages from the various channels. If there are no pending messages, then it should go back to schedule the next job.
