### ISSUE TITLE
Can you set a timed task in milliseconds?

### ISSUE THREAD

**Issue by beyondyinjl2** [robfig/cron#401]
Can you set a timed task in milliseconds?

**Comment by robfig** [comment]
Sorry, that's not possible with this library. I don't think that this library's approach is a good one for that use case, anyway. It would have much more overhead than is warranted.. Perhaps a simple looped sleep would suffice for your use case? 

```go
for {
  doTask()
  time.Sleep(50*time.Millisecond)
}
```
