### ISSUE TITLE
Run the process forever ?

### ISSUE THREAD

**Issue by mlexs** [robfig/cron#408]
How does one run a process using the `cron` package **indefinitely** ?

I would like to use this library and have my process to run "forever" (or "killed" by some other processes/actions when needed).

Below code runs forever but it gets CPU 100% after 8-10 secs.

```golang
c := cron.New()
c.AddFunc("@every 1s", func() { voidFreeSites() })
for {
  c.Start()
}
```

This will run fine.
```golang
c := cron.New()
c.AddFunc("@every 1s", func() { voidFreeSites() })
c.Start()

wg := sync.WaitGroup{}
wg.Add(1)
wg.Wait()
```

But is there shorter option?

BTW I cannot use `time.Sleep` as I'm unable to predict how long my process will run for.

**Comment by secake** [comment]
Like this？
```go
c := cron.New()
c.AddFunc("@every 1s", func() { voidFreeSites() })
c.Start()

select{}
```
