### ISSUE TITLE
Job executed even after killing the process?

### ISSUE THREAD

**Issue by jazzsaxmafia** [robfig/cron#413]
Hello, thank you for this great library. I am using it in my side projects and I love it.

There is an issue that I am seeing, which might not about this library, but I see this for the first time using it. 

I made a program that executes a function everyday at certain time, then ran it background. Then I killed it using `kill -9 {PID}` and re-ran the code (did this multiple time). 

The next day, I found out that the function was executed multiple times. Is this expected? When I rebooted the computer and ran the program once, the function is executed just one time, so I don't think I mistakenly ran the function multiple times in the code. Thanks!

**Comment by robfig** [comment]
I don't think this can be related to this library, since it doesn't do anything around process management or forking. Perhaps you killed the wrong process?
