### ISSUE TITLE
Run Cron Indefinitely

### ISSUE THREAD

**Issue by udayravuri** [robfig/cron#414]
Hi,
I'm wondering if there is a way to run the CRON job indefinitely instead of specifying a sleep between start & stop as below:
	// create a cron and start it
	c := cron.New()
	c.Start()

	// cron-job runs for the duration hours: jobPeriod as mentioned in the properties file.
	if jobPeriod >= 1 {
		time.Sleep(time.Duration(jobPeriod))
	}

	c.Stop()

**Comment by robfig** [comment]
Cron will run indefinitely if you don't call Stop(). If you need to prevent your program from exiting while it runs, you could run it via `cron.Run()` or use something like https://github.com/SentimensRG/ctx/tree/master/sigctx to block until SIGTERM is received:

```go
c.Start()
<-sigctx.New()  // blocks here
```

**Comment by udayravuri** [comment]
Thank you very much for the input
