### ISSUE TITLE
How to run a job "right now", then do it again after 24 hours, then again after 24 hours...

### ISSUE THREAD

**Issue by thisismydrive1997** [robfig/cron#415]
I read the "Interval" section in the documentation. The provided example is "@every 1h30m10s". But the job only executes the first time **AFTER** 1h30m10s from the moment I run `main.go`. What if I want it to execute **immediately** after I run `main.go`, then execute again every 1h30m10s? I do not want it to wait 1h30m10s before executing the first time.

Please help, thank you!

**Comment by lonnyzhang423** [comment]
I have a similar situation. The fact is that this library can't trigger a job immediately.

But you can run your job or func directly. Just like this:
```
//go yourFunc()
go yourJob.Run()
```

**Comment by robfig** [comment]
Exactly ^
