### ISSUE TITLE
Recommendation for running cron in replicated services

### ISSUE THREAD

**Issue by stx-mohamadarafat** [robfig/cron#417]
Hi, 
I have a question, if lets say my service is running cron jobs. But the service replica is set to 2 in the Kubernetes, this will cause the cron job to run twice at each schedule. Is there any design recommendation from the  robfig team to prevent this? 
Should we only have 1 replicas for a cron job running services or is there any other way?

**Comment by robfig** [comment]
That use case is out of scope for this library, but I think you could get something to work if you were to use a distributed lock via etcd or similar. You could have a hook which checks to see if it is the current holder of the lock, and if so executes the job, and if not returns a no-op job. 

Hope this helps!
