### ISSUE TITLE
the parser seemingly is not parsing the crontab command after the scheduling parameters

### ISSUE THREAD

**Issue by jxsl13** [robfig/cron#419]
the parser seemingly is not parsing the crontab command after the scheduling parameters

is that intentional, or did nobody have a use for that, yet?

**Comment by robfig** [comment]
It does not have builtin support for running shell commands. This library is meant to make schedules easy to express for triggering your custom code.

**Comment by jxsl13** [comment]
I meant to extract the command string from behind the scheduler expression. From a crontab formated file.
To work with the command string.

**Comment by robfig** [comment]
That was not considered to be in scope, sorry!
