### ISSUE TITLE
Cron Trigger on last 3 day of Month

### ISSUE THREAD

**Issue by afzalabbasi** [robfig/cron#421]
Hey all
Is there any way to trigger cron job on last three day of month?
Please help me on this problem
Thanks

**Comment by robfig** [comment]
I don't believe you can express that with the builtin cronspec schedule, but you can implement any logic you want that conforms to the `cron.Schedule` interface and use that to schedule jobs.

**Comment by afzalabbasi** [comment]
@robfig  okey thanks.
