### ISSUE TITLE
AddFunc working incorrectly, returns error on 6 digit schedule

### ISSUE THREAD

**Issue by Ivasan7** [robfig/cron#438]
When you provide the cron schedule according to the docs:
https://pkg.go.dev/github.com/robfig/cron?utm_source=godoc#hdr-CRON_Expression_Format
works fine however error is returned such:
`expected exactly 5 fields, found 6: [* /5 * * * *]`

This is not true if you check the docs though. Wrong error message.

**Comment by cedar12** [comment]
@Ivasan7 https://pkg.go.dev/github.com/robfig/cron/v3

**Comment by ue360** [comment]
package github.com/robfig/cron/v3 is not a main package

**Comment by Ivasan7** [comment]
Ahh, rookie mistake :)

**Comment by Ivasan7** [comment]
Seems to be present at v3 as well

**Comment by Ivasan7** [comment]
```go 
import 	cron "github.com/robfig/cron/v3" 

c := cron.New()
	_, err = c.AddFunc("/5 * * * * *", devices.do())
	if err != nil {
		return err
	}

```

error:

`"expected exactly 5 fields, found 6: [/5 * * * * *]"`
