### ISSUE TITLE
Improper statement in doc about job concurrency

### ISSUE THREAD

**Issue by andyxning** [robfig/cron#44]
The doc statements, below, makes me feel ambiguous.
> Callers may register Funcs to be invoked on a given schedule. Cron will run them in their own goroutines.

I think `cron` will run each cron job in different goroutines. I.e., `cron` will handle the concurrency about the jobs.   
However, after reading the code in [cron.go](https://github.com/robfig/cron/blob/master/cron.go#L153-L162), i find that `cron` just call the registered job and handle them sequentially. 
I think this statements may be more proper:
> Callers may registers Funcs to be invoked on a given schedule. 
> Single cron instance will run registered Funcs sequentially. 
> Different cron instances will be run concurrently by cron package itself.

**Comment by robfig** [comment]
Not sure I understand the distinction that you're making. The code that runs jobs does indeed start them sequentially, to run concurrently each in their own goroutine
```go
go e.Job.Run()
```
