### ISSUE TITLE
The question mark logic seems implemented wrongly

### ISSUE THREAD

**Issue by andyxning** [robfig/cron#45]
The doc said that:
> Question mark ( ? )
> 
> Question mark may be used instead of '*' for leaving either day-of-month or day-of-> week blank.

However, according to the code in [cron](https://github.com/robfig/cron/blob/master/parser.go#L78-L81), question mark and asterisk is equal.
```go
	if lowAndHigh[0] == "*" || lowAndHigh[0] == "?" {
		start = r.min
		end = r.max
		extra_star = starBit
        }
```

And ignoring the `day of week` will make it like adding asterisk as the value of `day of week`

**Comment by robfig** [comment]
I think they are supposed to be equivalent -- at least, I'm pretty sure that's both the standard behavior as well as what's said in the docs.
