### ISSUE TITLE
only run one instance 'cron.run()'

### ISSUE THREAD

**Issue by winxxp** [robfig/cron#46]
If call twice 
````go
func (c *Cron) Start() {
	c.running = true
	go c.run()
}
````

**Comment by elgs** [comment]
So is this a question or a statement?

**Comment by winxxp** [comment]
I mean `Start()` method shoud be a singleton method, to protected call `Start() ` many times, or appliction must be protected self.

**Comment by elgs** [comment]
@winxxp thanks. That makes sense. Probably the `Start` should be like this:

```
func (c *Cron) Start() {
	if c.running {
		return
	}
	c.running = true
	go c.run()
}
```

**Comment by winxxp** [comment]
thread-safe better.

**Comment by shurcooL** [comment]
Is there a good reason your application can't call `Start` once?

Or are you saying, _in case_ a poorly behaved application calls `Start` more than once, then `cron` should handle that situation better?

**Comment by winxxp** [comment]
I used zookeeper to elect master,  when network broken or other slave online,  all node recvived new nodes to elect new leader, if leader call start, or stop, sometime  the elected reslt is the leader  node also leader node, so it call twice or more. 

Now I protected it out Start/Stop self.
