### ISSUE TITLE
memory leak

### ISSUE THREAD

**Issue by yangbo-qc** [robfig/cron#466]
I wrote a test case and found that the memory has been rising, can you help me to see if it is a problem with my use or a memory leak, thank you.
But when I increase the number of tasks to 10000 level, this phenomenon will not appear.

system: MacOS 12.5 (m1)
go: 1.16
cron: github.com/robfig/cron/v3 v3.0.1
code:
```go
func TestCron(t *testing.T) {
	c := cron.New(cron.WithSeconds())
	c.Schedule(cron.Every(time.Second), cron.FuncJob(func() {}))
	c.Start()

	go func() {
		for {
			var ms runtime.MemStats
			runtime.ReadMemStats(&ms)
			memory := int64(float64(ms.Alloc))
			routines := runtime.NumGoroutine()
			fmt.Printf(">> runtime: routines: %d, memory: %d\n", routines, memory)
			time.Sleep(time.Second)
		}
	}()

	sig := make(chan os.Signal, 1)
	signal.Notify(sig, syscall.SIGINT, syscall.SIGTERM)
	<-sig
	
	// Output:
	// >> runtime: routines: 4, memory: 156304
	// >> runtime: routines: 5, memory: 166616
	// >> runtime: routines: 5, memory: 167528
	// >> runtime: routines: 5, memory: 167968
	// >> runtime: routines: 5, memory: 168808
	// >> runtime: routines: 5, memory: 169632
	// ...
}
```

**Comment by alittlecat-x** [comment]
There is a timer `var timer *time.Timer` in function `func (c *Cron) run()`, I think maybe because of using `time.NewTimer` on each time around and not closing it.

**Comment by gistGitUser** [comment]
Alloc is the same as HeapAlloc.

documentation info
`HeapAlloc is bytes of allocated heap objects.
"Allocated" heap objects include all reachable objects, as well as unreachable objects that the garbage collector has not yet free. Specifically, HeapAlloc increases as heap objects are allocated and decreases as the heap is swept and unreachable objects are freed. Sweeping occurs incrementally between GC cycles, so these two processes occur simultaneously, and as a result HeapAlloc tends to change smoothly (in contrast with the sawtooth that is typical of stop-the-world garbage collectors).`

**Comment by yangbo-qc** [comment]
When I delete the relevant cron code, there will still be this phenomenon, I understand that it may not be the problem of the library
