### ISSUE TITLE
Addfunc running every hour at 12th minute instead of every day at 12

### ISSUE THREAD

**Issue by TheStu** [robfig/cron#469]
It seems likely this is my own lack of understanding, and not actually a bug, but I can't see anything I'm doing wrong ...

```
c.AddFunc("0 12 * * *", func() {
...
}
```

This seems to run every hour, on the 12th minute. I would expect it to run every day at 12:00. Plugging that CRON expression in to [a CRON expression builder](https://crontab.guru/) seems to confirm that it should run once per day at 12:00. What am I doing wrong here?

**Comment by flyingrx** [comment]
From source code, the format starts from second, you'd better add a zero at front.
```
var standardParser = NewParser(
	Minute | Hour | Dom | Month | Dow | Descriptor,
)
```

**Comment by TheStu** [comment]
According to the readme the seconds are optional. I tried it anyway, just in case, but it didn't work.

**Comment by TheStu** [comment]
nvm, mistakenly installed an old version of the package.
