### ISSUE TITLE
I cannot pass second as 6th param for cronjob

### ISSUE THREAD

**Issue by iamatulsingh** [robfig/cron#497]
For my purpose it's required to make cron exact with seconds paran in cron param (* * * * * *). I tried but it's throwing error that it require only 5 params. I saw the code a little and found seconds option is available. 
Is there any way to fix this? By the way I'm using v3.

**Comment by baabeetaa** [comment]
from doc:
```
// Seconds field, required
cron.New(cron.WithSeconds())
```

**Comment by iamatulsingh** [comment]
@baabeetaa Thanks for the help!
