### ISSUE TITLE
how can i remove job when Cron is running?

### ISSUE THREAD

**Issue by cgyy** [robfig/cron#5]
func (c *Cron) RemoveJob(identifier string) {
	//remove job by identifier
}

i think add a method like this is useful

**Comment by robfig** [comment]
This feature was added in https://github.com/robfig/cron/commit/2b666ea6e8456493a58c35ee494f95ebe1207f38

Please let me know if it does not meet your needs.

**Comment by cgyy** [comment]
Yes, thanks， It's a great job!

**Comment by boernd** [comment]
Is this feature just available in the v2 branch and no tagged versions?
