### ISSUE TITLE
does this package support standard crontab expr

### ISSUE THREAD

**Issue by zhuliquan** [robfig/cron#502]
according to `README.md`, this package support [standard crontab expr](https://en.wikipedia.org/wiki/Cron)

Howevery, I find some expr run error.

For example. expr `* * * * *` means run every minute in standard crontab expr. (you can check meaning of crontab expr on this [website](https://crontab.guru/#*_*_*_*_*)). But in this package, I find it run every second. I'am very confused.

test code (in v1.2.0) 
```golang
package main

import (
	"fmt"
	"time"

	"github.com/robfig/cron"
)

func main() {
	job := cron.New()
	job.AddFunc("* * * * *", func() {
		fmt.Printf("run at %s\n", time.Now())
	})
	job.Start()

	select {}
}
```

**Comment by vfaberd** [comment]
@zhuliquan note that you are not using the latest version
Changing your import to `import "github.com/robfig/cron/v3"` should solve the problem
