### ISSUE TITLE
Job with @midnight sometimes execute every line of code twice 

### ISSUE THREAD

**Issue by ibmboy19** [robfig/cron#68]
my code is here:

```
cron := cron.New()
cron.AddFunc("@midnight", job.DoSomeJob)
cron.Start()
```

Sometimes every line of code in job.DoSomeJob will be executed twice.

**Comment by robfig** [comment]
The v1 branch used to have a bug that could cause this. I believe it was long ago fixed.. please try the v3 branch and let me know if you see anything wrong!
