### ISSUE TITLE
Call twice because of run time not accurate

### ISSUE THREAD

**Issue by mnhkahn** [robfig/cron#72]
I have a crontab job run every 10 minutes. I found that when it call at `2016/09/13 08:49:59`, it will call again at `2016/09/13 08:50:00`. It will then call twice.

**Comment by robfig** [comment]
Do you have a code snippet so I can try to reproduce?

**Comment by aobco** [comment]
@mnhkahn , I fixed it like this:  [cron.go:186]  now = now.In(c.location).Round(time.Second)

**Comment by robfig** [comment]
I believe that this is a dupe of #59. It should be fixed on v3.
