### ISSUE TITLE
Monthly job executed every day

### ISSUE THREAD

**Issue by sungwoncho** [robfig/cron#77]
I had a strange behavior:

I have a monthly job for sending out emails running at 8:30 first day of every month.

```go
	c := cron.New()
        ...
	c.AddFunc("15 8 1 * *", func() { EmailMonthlySummaries(db) })
	c.Start()
```

But the job executed every day for the three consecutive days. Any ideas what is going on?

**Comment by sungwoncho** [comment]
Just realized that the package is using a somewhat [different cron format](https://godoc.org/github.com/robfig/cron#hdr-CRON_Expression_Format) from the [one I am used to](http://www.nncron.ru/help/EN/working/cron-format.htm).

I will close this soon after I fix the code. Meanwhile, @robfig 

1. Is the format used by this library conventional?
2. Should there be a warning in README to prevent this kind of mishap? (happy to do PR improving the doc)

**Comment by robfig** [comment]
There is a relatively new ParseStandard method that may be what you were looking for
https://godoc.org/github.com/robfig/cron#ParseStandard

I suppose that could be integrated into the godoc Expression Format section..
