### ISSUE TITLE
Pass the JobID to the Job

### ISSUE THREAD

**Issue by jannickfahlbusch** [robfig/cron#85]
`cron.AddFunc()`/`cron.AddJob()` return the ID of the added job.

When `cron` runs the job, it should pass `Run()` the ID of the job.

**Comment by icholy** [comment]
The implementation doesn't assign id's to jobs. Also, changing the signatures of `AddFunc` and `AddJob` would be a pretty big breaking change. It's pretty simple to do yourself:

``` go
package main

import (
	"log"

	"github.com/robfig/cron"
)

var seq int

func nextID() int {
	seq++
	return seq
}

type job struct {
	id int
}

func (j *job) Run() {
	log.Println("JobID", j.id)
}

func main() {
	c := cron.New()

	jobID := nextID()
	c.AddFunc("...", &job{jobID})

	c.Run()
}
```
