### ISSUE TITLE
There is no way to wait for completion of started Jobs after calling Stop()

### ISSUE THREAD

**Issue by mrwonko** [robfig/cron#98]
When calling `Stop()` there may still be be Jobs whose Goroutines have been created but were never scheduled. It is therefore impossible to wait for all Jobs to complete, because some may not yet be running, making it impossible to track them.

The right place for adding to a `sync.WaitGroup` would be in `Cron:run()` right before `go c.runWithRecovery(e.Job)`. You could then add a new `Cron:Wait()` function for waiting for jobs to finish after calling `Stop()`.

**Comment by robfig** [comment]
I agree, this is very hard for users to do without support from cron. I will implement this.

**Comment by robfig** [comment]
This is now implemented. Have a look at the referenced commit for how to use it. Thanks
https://github.com/robfig/cron/commit/15ec73dd770fc76823127a51b72bd5a0b5b4c1e0

**Comment by mrwonko** [comment]
Great! Just keep the peculiarities of [WaitGroup.Add](https://golang.org/pkg/sync/#WaitGroup.Add) in mind:

> Note that calls with a positive delta that occur when the counter is zero must happen before a Wait.

So anybody wishing to re-use a Cron object now has to wait for the context returned by `Stop()` to complete before calling `Run()` again, or else there's a risk of the `Add()` call happening concurrently with `Wait()`.
